### PR TITLE
[15.0][FIX] stock_return_request: Fix string to translate

### PR DESCRIPTION
**Pull request by pedrobaeza**
The string to translate shouldn't be put with triple quote, or it becomes a hell to be translated. The Spanish translation was also incorrect, provoking the new PO linter to fail.

@Tecnativa

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul @gurneyalex it seems the bot is still not up.

**Pull request merged**
