### PR TITLE
[14.0][IMP] product_supplierinfo_for_customer_picking: customerinfo method

### PR DESCRIPTION
**Pull request by HekkiMelody**
Use the method provided by the base module to find the correct customerinfo

Second commit adds maintainers.

To do:
- [x] Depends on: https://github.com/OCA/product-attribute/pull/1497
- [x] add test coverage

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by PicchiSeba — APPROVED** [review]
Code review: LGTM

**Comment by francesco-ooops** [comment]
@pedrobaeza can this be merged as the consequence of https://github.com/OCA/product-attribute/pull/1497 ?

**Comment by pedrobaeza** [comment]
/ocabot merge minor

Friendly reminder: all of this improvements are not fw-ported, so when you switch to an upper version in the future, it will be a mess of code homogeneity.

**Comment by francesco-ooops** [comment]
> Friendly reminder: all of this improvements are not fw-ported, so when you switch to an upper version in the future, it will be a mess of code homogeneity.

Sadly I am well aware, but with current workload it's hard to imagine to fw-port and adapt for two (and soon 3) versions. 

I will check if we can get someone to focus on forward portings :)

**Pull request merged**
