### PR TITLE
[16.0][MIG] stock_picking_return_lot

### PR DESCRIPTION
**Pull request by sbejaoui**
- Add a lot field to the return wizard and create a return line for each lot/product combination.
- Use Stock Restrict Lot to track the accepted lot on the return picking.

image

image

image

image

cc/ @jbaudoux , @rousseldenis , @lmignon

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by jbaudoux — COMMENTED** [review]
Can you extract from the migration commit the enhancements so that the migration commit remains as small as possible ?

**Review by AungKoKoLin1997 — APPROVED** [review]
Code Review: LGTM

**Comment by sbejaoui** [comment]
> Can you extract from the migration commit the enhancements so that the migration commit remains as small as possible ?

done

**Review by jbaudoux — APPROVED** [review]
LGTM

**Pull request merged**
