### PR TITLE
[12.0][ADD] product_supplierinfo_picking

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
This module loads in every Stock move the supplier code defined in the product.

cc ~ @ForgeFlow

### CODE REVIEW

**Comment by CarlosRoca13** [comment]
I saw the fields on the form but I don't see them on the tree.

Can you specify the usage on the readme?

**Comment by AdriaGForgeFlow** [comment]
> I saw the fields on the form but I don't see them on the tree.
> 
> Can you specify the usage on the readme?

Done, can you check now?

**Review by CarlosRoca13 — APPROVED** [review]
:+1:

**Review by HviorForgeFlow — APPROVED** [review]
Code Review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
