### PR TITLE
8.0 sale link

### PR DESCRIPTION
**Pull request by Viggor**
Feature about parent-child relation of picking-line-sale-link ported to 8.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is like a mini-product_pack module, isn't it? What is the motivation for it?

**Comment by yvaucher** [comment]
Restarted travis

**Comment by yvaucher** [comment]
@Viggor can you rebase to trigger the right travis build (or at least git commit --amend you last commit), travis might fail as restarting it started again the old jobs

**Comment by Viggor** [comment]
This module is for choose optionnal bom line to make the manufacturing more flexible.
Still work in progress, may be move in a more appropriate repository.
Sorry for the answer delay.

**Comment by Cedric-Pigeon** [comment]
@Viggor Do you plan to achieve this PR ? Otherwise it will be closed in 3 days.

**Comment by pedrobaeza** [comment]
No answer, so I close it. Feel free to reopen if needed.

**Pull request closed without merging**
