### PR TITLE
Add security rule  for multicompany

### PR DESCRIPTION
**Pull request by archetipo**

### CODE REVIEW

**Comment by eLBati** [comment]
@opencode @archetipo is this duplicated of https://github.com/OCA/stock-logistics-workflow/pull/212 ?

**Comment by archetipo** [comment]
@eLBati maybe yes thanks ..

**Comment by elicoidal** [comment]
LGTM but should we need UT?

**Comment by eLBati** [comment]
@opencode @archetipo no, this is not duplicated of https://github.com/OCA/stock-logistics-workflow/pull/212

**Comment by gurneyalex** [comment]
:+1:

**Comment by eLBati** [comment]
LGTM :+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
