### PR TITLE
[14.0][MIG] product_supplierinfo_picking

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

CC @ForgeFlow

### CODE REVIEW

**Comment by ypapouin** [comment]
@HviorForgeFlow, can you force push to trigger a new runboat build? the last one is still `Pending`

**Comment by rousseldenis** [comment]
@HviorForgeFlow Could you check tests ?

**Comment by HviorForgeFlow** [comment]
@rousseldenis tests solved here: https://github.com/OCA/stock-logistics-workflow/pull/1170

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Comment by LoisRForgeFlow** [comment]
Sorry, I aborted momentaniously because I thought it was duplicated with https://github.com/OCA/stock-logistics-workflow/tree/14.0/product_supplierinfo_for_customer_picking, but it is not, one is for suppliers and other for customeres. Reissuing merge:

/ocabot merge nobump

**Pull request merged**
