### PR TITLE
[15.0][MIG] stock_putaway_hook

### PR DESCRIPTION
**Pull request by flachica**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
Wait a bit as code has changed in _get_putaway_strategy() method as it returns by default the location or its children : https://github.com/odoo/odoo/blob/15.0/addons/stock/models/stock_location.py#L268

I'm currently writing tests for this module.

@sebalix @flachica

**Comment by rousseldenis** [comment]
@flachica Take a look at https://github.com/OCA/stock-logistics-workflow/pull/1102

You should take the last two commits.

**Comment by flachica** [comment]
@rousseldenis How I can cherry pick yours two commits to my branch? I don't know the git commands to do this. I always pick with `git rebase -i 15.0` and edit to add `p hash_commit` before branch migration commit. But in this case . . .

**Comment by rousseldenis** [comment]
> @rousseldenis How I can cherry pick yours two commits to my branch? I don't know the git commands to do this. I always pick with `git rebase -i 15.0` and edit to add `p hash_commit` before branch migration commit. But in this case . . .

On your branch, do:

`git remote add acsone https://github.com/acsone/stock-logistics-workflow`
`git fetch acsone`
`git cherry-pick <commit sha>`
`git push`

**Comment by flachica** [comment]
@rousseldenis Thanks a lot for your work and for this expert class. Commits included. Waiting for tests results

**Review by sebalix — APPROVED** [review]

**Pull request merged**
