### PR TITLE
[17.0][MIG]stock_picking_origin_reference_sale

### PR DESCRIPTION
**Pull request by GuillemCForgeFlow**
Depends on https://github.com/OCA/stock-logistics-workflow/pull/1633

standard migration

cc @ForgeFlow

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Review by christian-ramos-tecnativa — APPROVED** [review]

**Review by jbernausVunkers — APPROVED** [review]

**Comment by hparfr** [comment]
The dependency has been merged; @GuillemCForgeFlow can you rebase ?

**Comment by GuillemCForgeFlow** [comment]
@hparfr just rebased, I have also done it for #1648 if you want to get it merged as well 🙂

**Review by hparfr — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
