### PR TITLE
[13.0][ADD] sale_line_returned_qty_mrp

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Depends on:

- [x] https://github.com/OCA/stock-logistics-workflow/pull/1043

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

If this only applies to kits I think you can put that in the module description

**Comment by JordiMForgeFlow** [comment]
Hi @AaronHForgeFlow 

Done! :)

**Review by JoanSForgeFlow — APPROVED** [review]
Code Review! LGTM :+1:

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! Functional review! :+1:

**Pull request merged**
