### PR TITLE
[12.0][MIG] stock_delivery_note: Migration to 12.0

### PR DESCRIPTION
**Pull request by antonio-trey**
Standard migration from 14.0 to 12.0.

### CODE REVIEW

**Review by MiguelPoyatos — APPROVED** [review]

**Comment by rousseldenis** [comment]
@antonio-trey Thanks for your contribution.

It seems that you didn't follow migration guide to do it. Some commits do not appear here. Especially the technical part.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch

You should replace git format patch source by 14.0 (instead of 11.0)

**Comment by antonio-trey** [comment]
> @antonio-trey Thanks for your contribution.
> 
> It seems that you didn't follow migration guide to do it. Some commits do not appear here. Especially the technical part.
> 
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch
> 
> You should replace git format patch source by 14.0 (instead of 11.0)

@rousseldenis Done! Thank you very much.

**Review by rousseldenis — APPROVED** [review]

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by MiguelPoyatos — APPROVED** [review]

**Pull request merged**
