### PR TITLE
[15.0][MIG] stock_picking_warn_message: Migration to 15.0

### PR DESCRIPTION
**Pull request by dhx**
Standard migration from 14.0 to 15.0

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by dhx** [comment]
@rousseldenis I'd also like to port #980 to 15.0 - does it make sense to include it in this PR or wait for this one to be merged and create a new one?

**Comment by dhx** [comment]
The module seems to work in our 15.0 deployments so far, @rousseldenis think it's ready to be merged?

**Comment by rousseldenis** [comment]
> The module seems to work in our 15.0 deployments so far, @rousseldenis think it's ready to be merged?

@dhx Ok, I can do it. Do we wait for forwardport or you'll do it later?

**Comment by dhx** [comment]
@rousseldenis forwardport is done

**Pull request merged**
