### PR TITLE
Correctly group move IDs depending on product and location

### PR DESCRIPTION
**Pull request by mdietrichc2c**
Issue : all the moves in picking dispatches were set as "available" if a combination of product/location was available. This only sets as "available" the ones used for `_product_reserve`.

### CODE REVIEW

**Comment by lepistone** [comment]
:+1: Thanks for fixing my bug @mdietrichc2c, and thanks to @tsauerwein for the tip on `ARRAY_AGG`.

**Comment by jcoux** [comment]
:+1:

**Comment by cyrilgdn** [comment]
Looks Good To Me  :+1:

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
