### PR TITLE
[16.0][ADD] Lock Done Quantity Changes in Stock Moves

### PR DESCRIPTION
**Pull request by sbejaoui**
This module limits the capability to modify the done quantity for stock moves
once they have been validated.

cc/ @jbaudoux

### CODE REVIEW

**Review by jbaudoux — APPROVED** [review]

**Comment by jbaudoux** [comment]
@rousseldenis Can you drop a review?

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@sbejaoui Could you rebase ?

**Comment by sbejaoui** [comment]
> @sbejaoui Could you rebase ?

done

**Comment by rousseldenis** [comment]
Tests are failing due to wrong inheritance in stock_picking_batch_validate_confirm module.

@Shide @EmilioPascual Could you fix it by doing a PR?

You cannot inherit from this test class:

https://github.com/OCA/stock-logistics-workflow/blob/16.0/stock_picking_batch_validate_confirm/tests/test_batch_confirm.py#L6

As that will launch the tests in stock modules here, which is unwanted.

**Comment by EmilioPascual** [comment]
> Tests are failing due to wrong inheritance in stock_picking_batch_validate_confirm module.
> 
> @Shide @EmilioPascual Could you fix it by doing a PR?
> 
> You cannot inherit from this test class:
> 
> https://github.com/OCA/stock-logistics-workflow/blob/16.0/stock_picking_batch_validate_confirm/tests/test_batch_confirm.py#L6
> 
> As that will launch the tests in stock modules here, which is unwanted.

Fix in https://github.com/OCA/stock-logistics-workflow/pull/1674

**Comment by hparfr** [comment]
@sbejaoui , please rebase

**Review by hparfr — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
