### PR TITLE
[14.0][MIG] purchase_stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by RabbitJon-S73**
purchase_stock_picking_invoice_link migration to 14.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@RabbitJon-S73 Thanks for this.

Could you check tests ?

Moreover, when doing PR's, don't forget to make a title prettier.

**Comment by RabbitJon-S73** [comment]
@rousseldenis done

**Review by victoralmau — APPROVED** [review]
Code review OK.

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
