### PR TITLE
[8.0]  [ADD] 'stock_picking_partial_invocing'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module was written to extend the invoicing capabilities of Odoo, and allows users to create customer or supplier invoices for part of a delivered Order or received Incoming Shipment.

Regards,
Jordi.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza I'm now adding the spanish translations (also manually added translations for computed fields), as well as the other suggestions that you made on the 7.0 version.

**Comment by pedrobaeza** [comment]
:+1: 

Thanks.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza I have added extra use cases to better handle situations such as the user deleting the invoice or an invoice line, or changing the invoice quantity.

**Comment by yvaucher** [comment]
Few PEP8 issues to fix

```
./stock_picking_partial_invoicing/__init__.py:23:1: W391 blank line at end of file
./stock_picking_partial_invoicing/model/account.py:22:1: F401 'fields' imported but unused
./stock_picking_partial_invoicing/model/account.py:26:1: E303 too many blank lines (3)
./stock_picking_partial_invoicing/model/account.py:100:19: W292 no newline at end of file
```

I restarted travis as failing tests for other modules were fixed in #111

**Comment by anajuaristi** [comment]
Hi... I tested the module following the next steps:
1. Go to demo data pickings
2. Select the ones from openelec, set "to invoice"
3. In tree view select 3 invoices
4. When wizard is shown, click group check, just delete one line not to be invoiced, push confirm button

I obtain this traceback:

```
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_dropshipping_dual_invoice/wizard/stock_invoice_onshipping.py", line 67, in open_invoice
    res = super(StockInvoiceOnshipping, self).open_invoice()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_account/wizard/stock_invoice_onshipping.py", line 105, in open_invoice
    invoice_ids = self.create_invoice(cr, uid, ids, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_dropshipping_dual_invoice/wizard/stock_invoice_onshipping.py", line 113, in create_invoice
    return super(StockInvoiceOnshipping, self).create_invoice()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_picking_partial_invoicing/wizard/stock_invoice_onshipping.py", line 107, in create_invoice
    res = super(StockInvoiceOnshipping, self).create_invoice()
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 547, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_account/wizard/stock_invoice_onshipping.py", line 148, in create_invoice
    context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_account/stock.py", line 267, in action_invoice_create
    invoices += self._invoice_create_line(cr, uid, moves, journal_id, type, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/delivery/stock.py", line 130, in _invoice_create_line
    invoice_ids = super(stock_picking, self)._invoice_create_line(cr, uid, moves, journal_id, inv_type=inv_type, context=context)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/3112818-103-e2dcf7/openerp/addons/stock_account/stock.py", line 319, in _invoice_create_line
    invoice_name = filter(None, [invoice.name, invoice_vals['name']])
KeyError: 'name'
```

Thank you

**Comment by anajuaristi** [comment]
Another test

Same way, take demo pickings
1. Set "to invoice" in 3 pickings
2. Show the wizard
3. This time, don't check group 
4. Delete one line

Push confirm button --> Expected behavior should be that only the invoices having ALL lines invoiced should be set to "invoiced". 
On the other side, the erased lines should not be invoiced and they are, since I'm obtaining 3 different invoices and not 2, as expected.

I think the module maybe has been tested to partially invoice a single picking but it hasn't been for invoicing several at once.

Sorry but from my side :-1:  until the issues are repared but I like the functionality is included on module :)

Thank you!!! @jbeficent

**Comment by pedrobaeza** [comment]
@jbeficent, any news on this?

**Comment by JordiBForgeFlow** [comment]
After fixing the issues reported by @anajuaristi are not reproduced. Also considered the review comments of @pedrobaeza.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza and @anajuaristi This one is now green.

**Comment by pedrobaeza** [comment]
By my part, :+1: 

@anajuaristi, can you check again?

**Comment by JordiBForgeFlow** [comment]
I'm substituing this PR with this one: https://github.com/OCA/stock-logistics-workflow/pull/192

**Pull request closed without merging**
