### PR TITLE
[15.0][IMP] stock_picking_batch_extended: Display operations and detailed operations from batch picking with smart buttons

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa 

ping @carlosdauden @pilarvargas-tecnativa

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by pilarvargas-tecnativa** [comment]
When I push the "Detailed op." button, I get an error:

```
Error: While parsing modifiers for button: for modifier "invisible": Unknown field parent.state in domain
```

Errorstockpickingbatch

**Comment by sergio-teruel** [comment]
Please try again!

**Review by pilarvargas-tecnativa — APPROVED** [review]
:+1:

**Pull request merged**
