### PR TITLE
[15.0][MIG] stock_owner_restriction: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36557

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review

**Comment by cesar-tecnativa** [comment]
@pedrobaeza please review

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by cesar-tecnativa** [comment]
@LudLaf could you review this?

**Comment by cesar-tecnativa** [comment]
@pedrobaeza could you review this?

**Review by pedrobaeza — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
