### PR TITLE
[15.0][MIG] stock_picking_group_by_partner_by_carrier: Migrate 14.0 to 15.0

### PR DESCRIPTION
**Pull request by ellbristow**

### CODE REVIEW

**Comment by ellbristow** [comment]
Waiting on https://github.com/OCA/stock-logistics-workflow/pull/1038

**Comment by sebalix** [comment]
@ellbristow https://github.com/OCA/stock-logistics-workflow/pull/1038 has been merged, can you rebase your PR please?

**Comment by rousseldenis** [comment]
@ellbristow

**Pull request closed without merging**
