### PR TITLE
[15.0][FIX] stock_picking_product_availability_search: avoid built-in 'type'

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Selection_698

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]
Thanks!

**Comment by ivantodorovich** [comment]
Could you rebase? It seems pre-commit is failing during merge command

**Comment by rousseldenis** [comment]
/ocabot merge patch

It seems to be a simple connection problem

**Comment by ivantodorovich** [comment]
Thanks!

**Pull request merged**
