### PR TITLE
add _link_invoice_to_picking method

### PR DESCRIPTION
**Pull request by chafique-delli**
I added the _link_invoice_to_picking method to be able to inherit in another module and so updating of other fields on stock move.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This can be done directly in `_create_invoice_line_from_vals`. The only piece you need is to return inv_line_id (what has to be done to not break inheritance in any case).

**Comment by eLBati** [comment]
@chafique-delli I agree you have to return `inv_line_id`.

@pedrobaeza I don't understand what you mean with

> This can be done directly in _create_invoice_line_from_vals

it is done in `_create_invoice_line_from_vals` yet, without the change of this PR

**Comment by pedrobaeza** [comment]
No, @chafique-delli is creating a new method `_link_invoice_to_picking`, so that's why I say that this new method is unneeded.

**Comment by sebastienbeau** [comment]
May you need some additionnal information. We are working on a module that management holding flow. A picking when is deliveried is invoiced by the current company and by the holding. The holding and the current company can have different rule for sending the invoice (I mean sometime the holding can invoice the customer first and sometime the current company invoice the holding before...). We are reusing the invoicing existing code the only trouble we have is at the end of the process this module will always link the invoice (current company or holding to the picking) in our case we want to write in the field "holding_inoice_id" instead of invoice_id. This is why we need to extract the "link" method between the picking and the invoice. The holding invoicing module is here : https://github.com/OCA/multi-company/pull/14

**Comment by eLBati** [comment]
@pedrobaeza ok so you say this PR is unneeded. Right

**Comment by eLBati** [comment]
@pedrobaeza @sebastienbeau that being said, I am not against the new method `_link_invoice_to_picking`, but `_create_invoice_line_from_vals` must keep returning `inv_line_id`

**Comment by sebastienbeau** [comment]
@eLBati done ;)

**Comment by tafaRU** [comment]
It needs a rebase since https://github.com/OCA/stock-logistics-workflow/pull/129 has been merged.

**Comment by Cedric-Pigeon** [comment]
@chafique-delli Hello, do you plan to achieve this PR ? Is it still usefull ? Otherwise it will be closed in 3 days. Thanks.

**Comment by rousseldenis** [comment]
@chafique-delli I close this one. Please feel free to reopen it if you want

**Pull request closed without merging**
