### PR TITLE
Add product-attribute dependency

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to add the `product-attribute`OCA branch, containing the module `product_customer_code`, and which is needed by the module `product_customer_code_picking` in this branch.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You should remove then from .travis.yml. Please take the occasion to move all the dependencies to oca_dependencies.txt (webkit-tools and stock-logistics-warehouse).

**Comment by gurneyalex** [comment]
@mdietrichc2c CI is red. Can you give it a look.

**Comment by Cedric-Pigeon** [comment]
@mdietrichc2c Hello, do you plan to achieve this PR ? Is it still usefull ? Otherwise it will be closed in 3 days. Thanks.

**Comment by rousseldenis** [comment]
@mdietrichc2c I will close this. Please feel free to reopen it if you want.

**Pull request closed without merging**
