### PR TITLE
[FIX] [16.0] stock_customer_deposit: Lines taken from deposit has 100% discount and the original price_unit

### PR DESCRIPTION
**Pull request by Shide**
Lines taken from deposit has 100% discount and the original price_unit

MT-6103 @moduon @EmilioPascual @rafaelbn @fcvalgar @Gelojr please review if you want :)

### CODE REVIEW

**Review by EmilioPascual — APPROVED** [review]
LGTM. 
@Shide thanks for fix.

**Review by fcvalgar — APPROVED** [review]
Functional review,

Thank you @Shide

**Review by Gelojr — APPROVED** [review]
Nice Job @Shide  LGTM
https://www.loom.com/share/93abd75ffdbc430baae845468e0a095a?sid=6b4cff1b-17bc-4bca-825c-11b88d73be40

**Pull request merged**
