### PR TITLE
[15.0][MIG] stock_receipt_lot_info

### PR DESCRIPTION
**Pull request by SergiCForgeFlow**
Supersedes [#982](https://github.com/OCA/stock-logistics-workflow/pull/982)

### CODE REVIEW

**Comment by rousseldenis** [comment]
@SergiCForgeFlow Thanks for this. As @LoisRForgeFlow marked it here: https://github.com/OCA/stock-logistics-workflow/pull/926#issue-1044924600

Isn't it time to add tests ?

**Comment by LoisRForgeFlow** [comment]
> @SergiCForgeFlow Thanks for this. As @LoisRForgeFlow marked it here: [#926 (comment)](https://github.com/OCA/stock-logistics-workflow/pull/926#issue-1044924600)
> 
> Isn't it time to add tests ?

@rousseldenis We did it in v16 https://github.com/OCA/stock-logistics-workflow/blob/16.0/stock_receipt_lot_info/tests/test_receipt_lot_info.py. v13 and v15 won't ever be merged becouse of the dependency to odoo PR. However, I'd like to keep PRs open because I use this module in this versions.

**Comment by LoisRForgeFlow** [comment]
So, I just found Odoo merged another PR with the needed hook for this module... I  have updated the name of the method and added some tests. This is now ready to merge

**Review by JoanSForgeFlow — APPROVED** [review]
Works as expected!

**Comment by rousseldenis** [comment]
@SergiCForgeFlow @LoisRForgeFlow IMHO, the module name is too vague as the USAGE.rst.

You say that this allows to enter 'info' about lots. But that's not true. This is used to enter the different dates (removal, alert, best before).

In addition, I would say those information should be computed automatically depending on the configuration on the product level if the product is based on expiration date (checkbox).

What I understand about the need of this is in some implementations, it is not possible to configure all the product alerts times and you want to fill it in on reception step. That should be explained either in CONTEXT or DESCRIPTION fragment.

Thanks

**Comment by LoisRForgeFlow** [comment]
> @SergiCForgeFlow @LoisRForgeFlow IMHO, the module name is too vague as the USAGE.rst.
> 
> You say that this allows to enter 'info' about lots. But that's not true. This is used to enter the different dates (removal, alert, best before).
> 
> In addition, I would say those information should be computed automatically depending on the configuration on the product level if the product is based on expiration date (checkbox).
> 
> What I understand about the need of this is in some implementations, it is not possible to configure all the product alerts times and you want to fill it in on reception step. That should be explained either in CONTEXT or DESCRIPTION fragment.
> 
> Thanks

Hi @rousseldenis 

I have aligned the readme to be more accurate in the comparison with current standard behavior.

Does this make more sense now?

**Review by JordiMForgeFlow — APPROVED** [review]
Code review LGTM

**Pull request merged**
