### PR TITLE
[14.0][FIX] stock_landed_costs_mrp_subcontracting: improve tests

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Due to failing tests https://github.com/OCA/stock-logistics-workflow/actions/runs/3730341223/jobs/6327283738

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@rousseldenis this fixes the broken tests. Can you review and merge?

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
@JordiBForgeFlow Minor update ?

**Comment by JordiBForgeFlow** [comment]
@rousseldenis OK! Go ahead and merge

**Pull request merged**
