### PR TITLE
[13.0][FIX] stock_picking_return_restricted_qty: Use Form in tests to avoid crash tests

### PR DESCRIPTION
**Pull request by sergio-teruel**
Crash test due to this Odoo commit 
https://github.com/OCA/OCB/commit/8ca10a8f39c6e6b8647a695aa543f008f01ba034
The wizard lines have the field uom_id related to move.product_uom and readonly=False, if you call directly to wiz.onchage_picking_id a write in stock move is executed.

cc @Tecnativa 
Ping @carlosdauden @CarlosRoca13

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis is still red

**Comment by pedrobaeza** [comment]
Can you please join both patches in the same PR to have green CI?

**Comment by sergio-teruel** [comment]
https://github.com/OCA/stock-logistics-workflow/pull/886

**Comment by pedrobaeza** [comment]
Replaced by #886

**Pull request closed without merging**
