### PR TITLE
[17.0][MIG] stock_valuation_layer_usage

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/stock-logistics-workflow/pull/1716

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
please rebase :)

**Comment by JasminSForgeFlow** [comment]
> please rebase :)

Done, Thanks

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by sebalix — APPROVED** [review]

**Pull request merged**
