### PR TITLE
[9.0] stock_split_picking from 10.0

### PR DESCRIPTION
**Pull request by lmignon**

### CODE REVIEW

**Review by zakiuu — APPROVED** [review]
code + functional test

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by ThomasBinsfeld** [comment]
ping @rousseldenis

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by yvaucher** [comment]
I closed #201 in favor of this one.

Don't forget to have a look at https://github.com/OCA/stock-logistics-workflow/issues/167 to avoid double work.

**Comment by rousseldenis** [comment]
@yvaucher Done

**Comment by LoisRForgeFlow** [comment]
This might need a rebase, it is quite old.

**Comment by rousseldenis** [comment]
@lreficent Will do it

**Comment by rousseldenis** [comment]
@lreficent Done

**Review by LoisRForgeFlow — APPROVED** [review]
Good for me if travis goes green

**Comment by ThomasBinsfeld** [comment]
This one is ready to be merged

**Pull request merged**
