### PR TITLE
[15.0][MIG] stock_quant_package_dimension

### PR DESCRIPTION
**Pull request by flachica**
Dependencies 

https://github.com/OCA/product-attribute/pull/1149
https://github.com/OCA/product-attribute/pull/1151

### CODE REVIEW

**Comment by rousseldenis** [comment]
@flachica Could you add depending PR's in your migration ones descriptions? It would help reviewer doing his job. Thanks

**Comment by flachica** [comment]
Sorry @rousseldenis 

Dependencies 

https://github.com/OCA/product-attribute/pull/1149
https://github.com/OCA/product-attribute/pull/1151

**Comment by flachica** [comment]
I'm testing this module in local environment and is failing. Test is using [demo data](https://github.com/flachica/stock-logistics-workflow/blob/15.0-mig-stock_quant_package_dimension/stock_quant_package_dimension/tests/common.py#L16). Would it be more correct to use products created for tests than to use demo data?. 
In my environment I do not install demo data. They are copies of anonymized production data

/cc @rousseldenis

**Comment by rousseldenis** [comment]
> I'm testing this module in local environment and is failing. Test is using [demo data](https://github.com/flachica/stock-logistics-workflow/blob/15.0-mig-stock_quant_package_dimension/stock_quant_package_dimension/tests/common.py#L16). Would it be more correct to use products created for tests than to use demo data?. In my environment I do not install demo data. They are copies of anonymized production data
> 
> /cc @rousseldenis

@flachica It's indeed recommended to create new data in tests. But is it related ?

**Comment by rousseldenis** [comment]
@flachica When doing a PR with external dependencies that are not merged yet, you can follow this in order to be able to test this PR with runboat and make tests running : https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Comment by flachica** [comment]
I don't understand the [error](https://github.com/OCA/stock-logistics-workflow/actions/runs/3902165836/jobs/6664894986)

**Comment by rousseldenis** [comment]
> I don't understand the [error](https://github.com/OCA/stock-logistics-workflow/actions/runs/3902165836/jobs/6664894986)


image



@flachica That's explained in my last comment.

When you open a PR that depends on another open one, you should include in a temporary test-requirements.txt file, the reference to the other(s) module. You can read the content of the link I pointed you.

**Comment by flachica** [comment]
Uf, it is embarrasing. I was undone the change. I have redo it but in this case, the dependency it [can't](https://github.com/OCA/stock-logistics-workflow/actions/runs/3909563819/jobs/6680778027) be downloaded

**Comment by rousseldenis** [comment]
> Uf, it is embarrasing. I was undone the change. I have redo it but in this case, the dependency it [can't](https://github.com/OCA/stock-logistics-workflow/actions/runs/3909563819/jobs/6680778027) be downloaded

In this case you have two dependencies to unmerged PR. So, missing one line in test-requirements.txt

**Comment by flachica** [comment]
> > Uf, it is embarrasing. I was undone the change. I have redo it but in this case, the dependency it [can't](https://github.com/OCA/stock-logistics-workflow/actions/runs/3909563819/jobs/6680778027) be downloaded
> 
> In this case you have two dependencies to unmerged PR. So, missing one line in test-requirements.txt

The [last one](https://github.com/OCA/product-attribute/pull/1151) was merged. The [first one](https://github.com/OCA/product-attribute/pull/1149) is not located and make it fail


The [test-requirements.txt](https://github.com/flachica/stock-logistics-workflow/blob/37d58023ff2297418dcddd72903939878cce1c39/test-requirements.txt#L2) line must be wrong. 

`odoo-addon-product_packaging_dimension @ git+https://github.com/OCA/product-attribute.git@refs/pull/1149/head#subdirectory=setup/product_packaging_dimension`

**Pull request closed without merging**
