### PR TITLE
[16.0][FIX] stock_picking_auto_create_lot: create new serial number for lots

### PR DESCRIPTION
**Pull request by dessanhemrayev**
This bug was discovered while working with this module #1567

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dessanhemrayev Thanks for this. Could you maybe add a test to avoid regression ?

**Comment by rousseldenis** [comment]
@dessanhemrayev

**Comment by dessanhemrayev** [comment]
> @dessanhemrayev

@rousseldenis  Thanks, I'll try to add a test for this
If you can tell me in which key to add the tests?

**Comment by dessanhemrayev** [comment]
@rousseldenis  check please)

**Review by rousseldenis — APPROVED** [review]

**Pull request closed without merging**
