### PR TITLE
[FIX] sale_stock_mto_as_mts_orderpoint: support product set

### PR DESCRIPTION
**Pull request by sebalix**
A product set in a SO line has several related moves for the different components.

### CODE REVIEW

**Comment by rousseldenis** [comment]
Maybe a little test for missing line ? https://codecov.io/gh/OCA/stock-logistics-workflow/pull/707/diff

**Comment by simahawk** [comment]
@sebalix ping

**Comment by sebalix** [comment]
@rousseldenis @simahawk updated
EDIT: seems the coverage is still not reached...
Locally with pdb both conditions are met when running the test, I do not understand why codecov is complaining here.

**Comment by rousseldenis** [comment]
> @rousseldenis @simahawk updated
> EDIT: seems the coverage is still not reached...
> Locally with pdb both conditions are met when running the test, I do not understand why codecov is complaining here.

@sebalix If you want to check which lines are not covered, github includes now those comments in PR files explorer : https://github.com/OCA/stock-logistics-workflow/pull/707/files

**Comment by sebalix** [comment]
@rousseldenis yep, that's my point :) with pdb I'm reaching the line 32 with my test, so I do not understand why it is complaining here.

**Comment by simahawk** [comment]
@rousseldenis @sebalix anything else to do here beside approving?

**Comment by sebalix** [comment]
@simahawk nothing, everything is done, excepting this strange story about coverage

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@rousseldenis good for you?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
