### PR TITLE
[14.0] [MIG] stock_picking_mass_action: Port PR form 12.0 to 14.0

### PR DESCRIPTION
**Pull request by sonhd91**
Migrate 14.0:
* [[14.0][MIG] - stock_picking_mass_action](https://github.com/OCA/stock-logistics-workflow/pull/849)
Port PR from 12.0 to 14.0
* [[12.0][FIX] stock_picking_mass_action: Error mass picking transfer mixing](https://github.com/OCA/stock-logistics-workflow/pull/626)

### CODE REVIEW

**Review by leemannd — APPROVED** [review]
Technical review

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by sebalix — CHANGES_REQUESTED** [review]
This addon has already been merged through #973 , you need to keep only the last commit here:
`[FIX] stock_picking_mass_action: Error mass picking transfer mixing complete and partial`

**Comment by andreampiovesana** [comment]
merge?

**Pull request merged**
