### PR TITLE
[14.0][MIG] stock_picking_invoice_link: Migration to 14.0

### PR DESCRIPTION
**Pull request by joao-p-marques**
@Tecnativa 
TT26455

ping @pedrobaeza @chienandalu

### CODE REVIEW

**Comment by joao-p-marques** [comment]
This superseeds https://github.com/OCA/stock-logistics-workflow/pull/718

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
:+1:

**Pull request merged**
