### PR TITLE
[14.0] stock_picking_group_by_partner_by_carrier: Bump dev status

### PR DESCRIPTION
**Pull request by grindtildeath**
Required for CI after a bunch of modules depending on this one either had their dev status bumped as well or don't have any dev status. Cf:

- https://github.com/OCA/wms/actions/runs/6628639166/job/18006169885?pr=566#step:6:5
- https://github.com/OCA/wms/blob/14.0/stock_picking_type_shipping_policy/__manifest__.py#L7

### CODE REVIEW

**Comment by grindtildeath** [comment]
Runboat broken due to https://github.com/OCA/stock-logistics-workflow/pull/1271#issuecomment-1764497132

**Review by simahawk — APPROVED** [review]
IMO it can even been set as prod/stable

**Comment by grindtildeath** [comment]
@simahawk done.

**Review by rousseldenis — APPROVED** [review]

**Comment by simahawk** [comment]
It won't be that easy... :rofl: 

image

**Comment by grindtildeath** [comment]
@simahawk it's :green_circle: !

**Review by ivantodorovich — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Pull request merged**
