### PR TITLE
[16.0] [REF] stock_picking_batch_extended: Move settings option under Batch Picking group

### PR DESCRIPTION
**Pull request by Shide**
UX Improvement: Move settings option under Batch Picking group.

image

MT-3611 @moduon @rafaelbn @yajo please review :)

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍🏼

**Review by carlosdauden — APPROVED** [review]

**Comment by Shide** [comment]
Rebased because https://github.com/OCA/stock-logistics-workflow/pull/1399

**Comment by rafaelbn** [comment]
Wait please until @Gelo-fl send here the new screenshot for the README with the change 😄

**Comment by Gelojr** [comment]
Requested change of image in #1399

**Review by Gelojr — APPROVED** [review]
LGTM https://www.loom.com/share/76fca47341ff43d19674e283986ed559?sid=7b3ec68b-9f07-43b4-a323-8b91fa3f355a
Thanks @Shide

**Comment by RodrigoBM** [comment]
@Shide can you change de img that comment @Gelojr  https://github.com/OCA/stock-logistics-workflow/pull/1404#issuecomment-1775520835

**Comment by RodrigoBM** [comment]
> @Shide can you change de img that comment @Gelojr [#1404 (comment)](https://github.com/OCA/stock-logistics-workflow/pull/1404#issuecomment-1775520835)

@Shide I have created a pr for you for the image change https://github.com/moduon/stock-logistics-workflow/pull/1

**Comment by Shide** [comment]
@rafaelbn merge of @RodrigoBM done

**Comment by RodrigoBM** [comment]
Can @Shide rebase all commit to one commit? Thanks

**Comment by Shide** [comment]
@RodrigoBM done with squash

**Review by RodrigoBM — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
/ocabot merge minor

**Comment by rafaelbn** [comment]
@Shide please review https://github.com/OCA/stock-logistics-workflow/commits/de7194e50ce1411ffffc7281823c0b5a16e94306

**Comment by Shide** [comment]
@rafaelbn rebased and pre-commit fixed

**Pull request merged**
