### PR TITLE
[12.0][MIG] product_supplierinfo_for_customer_picking

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

- [x] Depends of https://github.com/OCA/product-attribute/pull/515.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on runbot.

**Comment by AaronHForgeFlow** [comment]
> Standard migration.
> 
> * [ ]  Depends of [OCA/product-attribute#515](https://github.com/OCA/product-attribute/pull/515).

Dependency is now merged @mreficent, this PR is ready

**Pull request merged**
