### PR TITLE
Add a wizard to check availability of a selection of dispatches

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1: (code review, no test)

**Comment by guewen** [comment]
I removed 'progress' from the states checked by the cron, because these dispatches are normally already available.

**Comment by rdeheele** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by gurneyalex** [comment]
@guewen needs rebase

**Comment by guewen** [comment]
Rebased

**Comment by yvaucher** [comment]
rerebased

addition of an other wizard was conflicting

**Comment by yvaucher** [comment]
only pep8 errors due to more restricted flake8

:+1:

**Pull request merged**
