### PR TITLE
[14.0] [ADD] stock_picking_reallocation

### PR DESCRIPTION
**Pull request by paradoxxxzero**
This module adds a reallocate button to dispatch a picking moves between several new pickings.

It uses a stored instance to allow saving current dispatching for later.

### CODE REVIEW

**Comment by hparfr** [comment]
Create a reallocation, change the first date and the second.
Then the schedule date of the first and the second is the same.

And if possible, it's better if the backorder is always the second picking.

**Review by hparfr — APPROVED** [review]
LGTM thanks

**Comment by mourad-ehm** [comment]
Hi @rousseldenis, could you reopen this PR ?

**Review by mourad-ehm — APPROVED** [review]
Code review

**Pull request merged**
