### PR TITLE
[MIG][10] Migration of module stock_picking_show_return

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by fmdl** [comment]
From : https://github.com/OCA/stock-logistics-workflow/pull/287

**Comment by pedrobaeza** [comment]
Please use migration guide for respecting commit history. In this case, it's more difficult due to renaming, but just rename the module in 10.0 before and then apply the guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0)

**Comment by pedrobaeza** [comment]
You are still missing commit history. I'll do it later and put exact commands.

**Comment by pedrobaeza** [comment]
OK, here you have it: https://github.com/OCA/stock-logistics-workflow/pull/314

The steps are:

- Rename original files in 10.0 branch:
```
git mv stock_picking_show_returns stock_picking_show_return
mkdir stock_picking_show_return/models
mkdir stock_picking_show_return/views
git mv stock_picking_show_return/stock_picking.py stock_picking_show_return/models
git mv stock_picking_show_return/stock_picking_view.xml stock_picking_show_return/views
```
- Commit this
- Make `git format-patch --stdout origin/10.0..origin/9.0 -- stock_picking_show_return | git am -3`
- Resolve several conflicts continuing with `git am --continue`.
- Add last commit with the migration.

**Comment by fmdl** [comment]
Please do the migration I understand nothing what I will do. I have use lot of hour to do a simple copy/past from V9 branch, it is too much for me, to complex.

Thank for you help.

Regards

**Comment by pedrobaeza** [comment]
I have already done it yesterday in #314. I have only explained to you for the next time to teach you how to do it, but I'm afraid you are still missing something. Please follow again the steps I have put if you want to learn these processes and let me know any doubt.

**Pull request closed without merging**
