### PR TITLE
[15.0][MIG] stock_picking_auto_create_lot

### PR DESCRIPTION
**Pull request by vib-adhoc**

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Code and functional review, LGTM

**Comment by LoisRForgeFlow** [comment]
@vib-adhoc There are some checks pending to attend in pre-commit, could you have a look? https://github.com/OCA/stock-logistics-workflow/runs/7893283265?check_suite_focus=true#step:7:92

**Review by rousseldenis — APPROVED** [review]

**Comment by vib-adhoc** [comment]
@LoisRForgeFlow @rousseldenis I added return in _compute_display_assign_serial for pre-commit checks, is that right?

**Comment by LoisRForgeFlow** [comment]
It is fine, let's merge :)

/ocabot merge nobump

**Pull request merged**
