### PR TITLE
 [17.0][MIG] stock_quant_package_product_packaging

### PR DESCRIPTION
**Pull request by ferran-S73**
Standard migration

### CODE REVIEW

**Review by traitrantrobz — APPROVED** [review]
LGTM 👍

**Comment by traitrantrobz** [comment]
@OCA-git-bot migration stock_quant_package_product_packaging. Please add it to [Issues Migration to 17.0](https://github.com/OCA/stock-logistics-workflow/pull/1618)

**Comment by rousseldenis** [comment]
> @OCA-git-bot migration stock_quant_package_product_packaging. Please add it to [Issues Migration to 17.0](https://github.com/OCA/stock-logistics-workflow/pull/1618)

@traitrantrobz Manual action :sweat_smile: 

/ocabot migration stock_quant_package_product_packaging

**Comment by ferran-S73** [comment]
@OCA/logistics-maintainers

**Review by jbaudoux — APPROVED** [review]

**Comment by rousseldenis** [comment]
@ferran-S73 Commit message for pre-commit should respect some convention:

image


See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#how-to

**Comment by rousseldenis** [comment]
Could you fix tests?

**Comment by ferran-S73** [comment]
@rousseldenis I think this should be ready to merge now

**Pull request merged**
