### PR TITLE
[15.0] [MIG] sale_line_returned_qty

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! :smile:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional

**Pull request merged**
