### PR TITLE
[MIG] stock_return_request: Migration to 12.0

### PR DESCRIPTION
**Pull request by chienandalu**
cc @Tecnativa TT21139

### CODE REVIEW

**Comment by manuelcalerosolis** [comment]
Code review: It's OK for me.
Functional review: OK (I test it locally)

**Review by manuelcalerosolis — APPROVED** [review]
Code review: It's OK for me.
Functional review: OK (I test it locally)

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
