### PR TITLE
[12.0][MIG] stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Standard migration of module stock_picking_invoice_link to v12

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's already #470

**Comment by ageficent** [comment]
> There's already #470

Damn, I hadn't noticed. Thanks :+1:

**Comment by rousseldenis** [comment]
Uh that's me or sale != invoice ? :smile:

**Comment by pedrobaeza** [comment]
What do you mean, @rousseldenis ?

**Comment by AdriaGForgeFlow** [comment]
@pedrobaeza The PR you referenced is the migration of stock_picking_sale_order_link, this one is the migration of stock_picking_invoice_link

**Comment by rousseldenis** [comment]
@pedrobaeza wrong ref in migration issue

**Comment by pedrobaeza** [comment]
Ouch, the problem was on the migration issue (but probably on my side too):

Selección_022

**Review by luismontalba — APPROVED** [review]
Tested on runbot

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
