### PR TITLE
[16.0][FIX] stock_picking_invoice_link: Avoid inconsistent computes

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Related to https://github.com/OCA/stock-logistics-workflow/pull/1620

@pedrobaeza @chienandalu In fact, you changed the 'store' attribute of 'picking_count' field. But this is incoherent as two fields should not be computed with the same method if one is store and not the other one.

This fixes that problem highlighted by the warning in Odoo log.

This is the log now: 

image


https://github.com/OCA/stock-logistics-workflow/actions/runs/9513693545/job/26224323631?pr=1625#step:8:675

**Comment by chienandalu** [comment]
Thanks @rousseldenis I'll fix that

**Comment by rousseldenis** [comment]
> Thanks @rousseldenis I'll fix that

We can merge this

**Review by chienandalu — APPROVED** [review]
oh, sorry, I thought it was my PR. Sure! :+1:

**Review by pedrobaeza — APPROVED** [review]
Thanks for the investigation, @rousseldenis 

@chienandalu this is happening the same in v17 and v15.

/ocabot merge patch

**Comment by rousseldenis** [comment]
> Thanks for the investigation, @rousseldenis
> 
> @chienandalu this is happening the same in v17 and v15.
> 
> /ocabot merge patch

Welcome.

I don't desperate to have this : https://github.com/orgs/community/discussions/11592

**Comment by chienandalu** [comment]
> @chienandalu this is happening the same in v17 and v15.

I'll take care of it

**Pull request merged**
