### PR TITLE
[11.0][ADD] stock_batch_picking: Create multiple batchs depends on grouped fields selected in wizard

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM

**Review by carlosdauden — APPROVED** [review]

**Comment by rousseldenis** [comment]
@pedrobaeza I think there was a hang during travis install in merge branch. Relaunching the merge command may success

**Comment by pedrobaeza** [comment]
Yes, it seems so, so /ocabot merge minor

**Comment by sbidoul** [comment]
For some reason, GitHub has not noticed travis is done. Trying again.

/ocabot merge minor

**Pull request merged**
