### PR TITLE
[MIG] stock_cost_method_last to 12.0

### PR DESCRIPTION
**Pull request by iwkse**

### CODE REVIEW

**Comment by GSLabIt** [comment]
@iwkse check travis

**Review by GSLabIt — CHANGES_REQUESTED** [review]
@iwkse  Thanks for your contribution. Can you follow migration guide here and especially about keeping commit history. Thanks.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

**Comment by rousseldenis** [comment]
Duplicate of #721 

@iwkse Could you ask there if this can replace it ?

**Comment by iwkse** [comment]
> Duplicate of #721
> 
> @iwkse Could you ask there if this can replace it ?

done

**Comment by iwkse** [comment]
@rousseldenis As for the linting issues, I see there's errors related to other modules, what should I do? Correct them as well?
Let me know

**Comment by gurneyalex** [comment]
This is a nice module but it should come with a warning about the lack of real time valuation support.

**Comment by rousseldenis** [comment]
@iwkse What's the status of this ?

**Comment by francesco-ooops** [comment]
> @iwkse What's the status of this ?

he will not keep working on it, I think you can close

**Pull request closed without merging**
