### PR TITLE
[WIP][ADD] New module 'stock_reception_screen'

### PR DESCRIPTION
**Pull request by sebalix**
Dedicated screen to scan and receive goods.

TODO: screenshots/gif

Development status: alpha

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this barcode related? Do you know https://github.com/OCA/stock-logistics-barcode/tree/11.0/stock_barcodes?

**Comment by sebalix** [comment]
@pedrobaeza it is barcode related yes, didn't see this module, need to check that, thanks! This module also adds a workflow to receive goods, guiding the operator step by step.

**Comment by pedrobaeza** [comment]
Then this should go to OCA/stock-logistics-barcode. And the linked module also does the reception.

**Comment by rousseldenis** [comment]
@sebalix Do you transfer this one to barcode repo as suggested by @pedrobaeza or keep it here?

**Comment by sebalix** [comment]
@rousseldenis I'll transfer it, no problem.

**Comment by rousseldenis** [comment]
So, closing this

**Comment by sebalix** [comment]
Moved to https://github.com/OCA/stock-logistics-barcode/pull/225

**Pull request closed without merging**
