### PR TITLE
[16.0][FIX] stock_picking_auto_create_lot: immediate transfer with auto_create_lot option

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
I accidentally closed the brach of this PR https://github.com/OCA/stock-logistics-workflow/pull/1283
Superseded by current PR.

@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Relaying my previous approval of the other PR.

**Review by rousseldenis — APPROVED** [review]
Code review. Seems fair

**Review by kanda999 — APPROVED** [review]

**Comment by AungKoKoLin1997** [comment]
@OCA-stock-logistics-workflow-maintainers
Can we get this PR merged?

**Pull request merged**
