### PR TITLE
[14.0][FIX] sale-stock_mto_as_mts_orderpoint

### PR DESCRIPTION
**Pull request by TDu**
On sale confirmation generate the procurement if the rule is on the sale order line OR the rule is activated on the product.

### CODE REVIEW

**Review by vuwnevska — APPROVED** [review]
looks LG

**Review by jbaudoux — APPROVED** [review]
LGTM

**Review by mmequignon — APPROVED** [review]

**Comment by jbaudoux** [comment]
Oups, some tests are failing... Needs to be fixed

**Comment by jbaudoux** [comment]
Let's backport this https://github.com/OCA/stock-logistics-orderpoint/pull/19/files#diff-76ea6961adcc7fcae2548e77a7d16d0b52753ce5b4cf891408a796751b89f4bcR10 to solve the failing tests

**Comment by TDu** [comment]
Here is the backport https://github.com/OCA/stock-logistics-workflow/pull/1698
But the 14.0 branch is actually not red :thinking:

**Pull request merged**
