### PR TITLE
[12.0][IMP] stock_picking_send_by_mail: Display send button for incoming picking too.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT27328

ping @carlosdauden @chienandalu

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]
LGTM 👍

**Comment by pedrobaeza** [comment]
Needed in v13?

**Comment by sergio-teruel** [comment]
Suggested in the migration PR https://github.com/OCA/stock-logistics-workflow/pull/658#issuecomment-747713894

**Pull request merged**
