### PR TITLE
Improve README.rst. Follow template recommendation

### PR DESCRIPTION
**Pull request by Doscaal**
Follow template recommendation and add some missing contributors

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
This module is for now not valid, because it creates inconsistent data. Does it worth to fix the README?

**Comment by florian-dacosta** [comment]
In my opinion, it can't hurt, so :+1:

**Comment by pedrobaeza** [comment]
OK, let's go then

**Pull request merged**
