### PR TITLE
[16.0][MIG] stock_picking_auto_create_lot_qty

### PR DESCRIPTION
**Pull request by dessanhemrayev**
Migration to 16.0

### CODE REVIEW

**Review by Bearnard21 — APPROVED** [review]
Functional test Ok

**Review by angelinaanaki — APPROVED** [review]
Code LGTM

**Review by Bearnard21 — CHANGES_REQUESTED** [review]
lease check how the module is working in multi-company env.

Steps to reproduce:
- Create a second company
- Install, Sales, Purchase, Inventory
- Setup second company Warehouse
- Activate Dropship Route
- Try To dropship items for any of the companies
-Try to Receive goods for any of the  companies

Expected behaviour:
- Amount of items is split and lots being assigned 

Current Behaviour:
- Amount is not being split and lots aren't assigned

**Review by Bearnard21 — APPROVED** [review]
Functionality OK

**Pull request closed without merging**
