### PR TITLE
[13.0][MIG] stock_picking_restrict_cancel_with_orig_move

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@grindtildeath Can you check travis ?

**Comment by grindtildeath** [comment]
@rousseldenis Changed the override of `_push_apply` to an override of `_merge_moves` as the latter should be called by the former anyway

**Review by rousseldenis — APPROVED** [review]
LGTM

**Review by guewen — APPROVED** [review]

**Pull request merged**
