### PR TITLE
[10.0][IMP] stock_picking_line_sequence: add sequence to delivery slip report

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Selection_073

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
travis error unrelated

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@mreficent when you create a reservation, which creates pack operations, and print the sequence is not appearing, because only pack operations are listed.

IMHO after https://github.com/odoo/odoo/blob/10.0/addons/stock/report/report_deliveryslip.xml#L81 you need to add:
`                                <td>
                                    <t t-if="pack_operation.linked_move_operation_ids">
                                        <span t-field="pack_operation.linked_move_operation_ids[0].move_id.sequence2"/>
                                    </t>
                                </td>`

**Comment by MiquelRForgeFlow** [comment]
@jbeficent good! thanks! done!

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional review

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
