### PR TITLE
[15.0][MIG] stock_picking_origin_reference_sale

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow 

Depends on:

- https://github.com/OCA/stock-logistics-workflow/pull/1341

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
Code review LGTM

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by LoisRForgeFlow — APPROVED** [review]
Strictly speaking the version bump should happen in the migration commit, but not blocking for me

**Comment by LoisRForgeFlow** [comment]
Straight forward migration, dependency is already merged:

/ocabot migration stock_picking_origin_reference

/ocabot merge nobump

**Pull request merged**
