### PR TITLE
[11.0][IMP]stock_picking_show_return

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
* include a button from the original picking to the return

### CODE REVIEW

**Comment by rousseldenis** [comment]
@AaronHForgeFlow Can you check flake8 ?

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍

**Comment by AaronHForgeFlow** [comment]
cc @ForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
