### PR TITLE
Fix travis build (flake8 W503)

### PR DESCRIPTION
**Pull request by gurneyalex**
move binary operators before line breaks where necessary. 

bonus: don't manually install coveralls and flake8  (handled by travis_install_nightly)

### CODE REVIEW

**Comment by gurneyalex** [comment]
Reviews and fast track welcome to fast track this PR

**Comment by lmignon** [comment]
:+1:

**Comment by lepistone** [comment]
:+1: thanks

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
