### PR TITLE
[16.0][MIG] product_expiry_simple

### PR DESCRIPTION
**Pull request by dreispt**
Closes #1320

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dreispt The merge commit seems weird: https://github.com/OCA/stock-logistics-workflow/pull/1533/commits/c85727a51628abb524b034b9ad1e6ef0a5bf0d1d

Why all those changes ?

**Comment by rousseldenis** [comment]
And why not letting the other PR be merged ?

**Comment by dreispt** [comment]
It seemed inactive. No concerns closing this.

**Pull request closed without merging**
