### PR TITLE
8.0 move to stock logistics transport

### PR DESCRIPTION
**Pull request by gurneyalex**
to be merged at the same time as
- [x] https://github.com/OCA/stock-logistics-transport/pull/8
- [x] https://github.com/OCA/stock-logistics-transport/pull/7
- [x] https://github.com/OCA/stock-logistics-transport/pull/4

### CODE REVIEW

**Comment by pedrobaeza** [comment]
What about enabling runbot for this one that it's going to be simpler than another repositories and you'll easy the review process?

**Comment by gurneyalex** [comment]
@pedrobaeza good idea.

**Comment by yvaucher** [comment]
:+1:

**Comment by jgrandguillaume** [comment]
Thanks for the work ! :+1:

**Comment by gurneyalex** [comment]
runbot and travis are green, related PRs are merged, I'm merging this.

**Pull request merged**
