### PR TITLE
Requires "Setting" access rights to access documents

### PR DESCRIPTION
**Pull request by Espzai**
Fix the issue to access pickings from invoices and vice versa.
This will solve this problem.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Espzai Thanks for this. Could you provide more information about which access error you have (screenshot) ?

**Comment by Espzai** [comment]
> @Espzai Thanks for this. Could you provide more information about which access error you have (screenshot) ?

@rousseldenis 
```
action = self.env.ref("stock.action_picking_tree_all")
result = action.read()[0]
```
here read requires "Administration/setttings" rights. Either we do it as result = action.sudo().read()[0]
or we use the proposed method in the PR directly where Odoo is using sudo() to read the action.

Screenshot from 2021-08-23 16-46-14

Regards.

**Comment by rousseldenis** [comment]
> > @Espzai Thanks for this. Could you provide more information about which access error you have (screenshot) ?
> 
> @rousseldenis
> 
> ```
> action = self.env.ref("stock.action_picking_tree_all")
> result = action.read()[0]
> ```
> 
> here read requires "Administration/setttings" rights. Either we do it as result = action.sudo().read()[0]
> or we use the proposed method in the PR directly where Odoo is using sudo() to read the action.
> 
> Screenshot from 2021-08-23 16-46-14
> 
> Regards.

Indeed, that's the good way to do it.

**Review by rousseldenis — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash commits into one and pass pre-commit

**Comment by rousseldenis** [comment]
@Espzai Could you squash your commits as @pedrobaeza said ?

Moreover with a more significant message

**Comment by rousseldenis** [comment]
Closing this as it has been done in another PR.

**Pull request closed without merging**
