### PR TITLE
[MIG][10.0] stock_picking_show_return

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by fmdl** [comment]
I have change of login (before @IguanaYachts). Regards

**Comment by pedrobaeza** [comment]
Please use migration guide for retrieving latest commits from 9.0 branch: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by pedrobaeza** [comment]
You are not preserving commit history and doing again the work. Please attend my comments.

**Comment by fmdl** [comment]
I not the best in git, I don't how what is the process to keep the history.

**Comment by pedrobaeza** [comment]
Just follow the migration guide I have put before.

**Pull request closed without merging**
