### PR TITLE
[15.0][MIG] stock_picking_batch_extended: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36560

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@sergio-teruel please review

**Comment by cesar-tecnativa** [comment]
@pedrobaeza please review

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review LGTM!

**Comment by florenciafrigieri2** [comment]
@pedrobaeza Hi Pedro! Can you please review this PR? Thanks!

**Review by nicomacr — APPROVED** [review]
LGTM

**Comment by sergio-teruel** [comment]
REFACTOR done (https://github.com/OCA/stock-logistics-workflow/pull/1041/commits/4cddfd8ee44a86754be061e6f42df8dda72cd0be)

Odoo has improved the batch pickings in v15, so I refactor this module to use the base module

**Pending fix tests and Migration scripts**

**Comment by sergio-teruel** [comment]
ping @carlosdauden @chienandalu

**Review by chienandalu — COMMENTED** [review]
- The readme should be refactored as well to leave just what the module adds right now.
- No migration scripts needed after the refactor?

**Comment by sergio-teruel** [comment]
@chienandalu Migration script done

**Review by carlosdauden — APPROVED** [review]
Great job @sergio-teruel

**Review by chienandalu — APPROVED** [review]
Wow, you really put it on diet :smile: :+1:

**Pull request merged**
