### PR TITLE
[ADD] stock_picking_auto_group: New module to automatically create procurement groups on individual stock pickings.

### PR DESCRIPTION
**Pull request by ryanc-me**
This module allows for procurement groups to be created automatically on stock pickings.

Especially useful in the case where products are being transferred between 2 locations, but in separate stock pickings, e.g. 5x separate transfers from `Location A` to `Location B`. By default, the receipts on `Location B` may be merged into a single receipt. This module will ensure that all 5 pickings have their own receipts.

Additionally, it provides a nice way to view all sub-pickings generated by push/pull rules. Clicking on the procurement group (from any picking in the chain) will show the entire picking chain.

A few notes:
 - The procurement group will propagate through the push/pull chain as per default Odoo functionality.
 - This feature can be enabled or disabled on specific stock picking types.
 - If a procurement group is already set on a picking, a new one will not be created.

### CODE REVIEW

**Comment by ryanc-me** [comment]
What is the OCA's policy on multi-commit PRs like this - should I rebase and squash, or force-push?

**Comment by GSLabIt** [comment]
squash

**Comment by ryanc-me** [comment]
> squash

@GSLabIt just to be clear, should I squash from my side, or will one of the PSR members squash when they review/merge the code?

**Comment by GSLabIt** [comment]
@ryanc-me you should squash

**Comment by rousseldenis** [comment]
@ryanc-me What's the status of this ?

**Pull request closed without merging**
