### PR TITLE
[17.0][MIG] stock_picking_invoice_link: Migration to 17.0

### PR DESCRIPTION
**Pull request by lethuthao2403**
ref: [BSRD-699](https://jira.camptocamp.com/browse/BSRD-699)

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Comment by loicgrifnee** [comment]
There seems to be an error in the way of overriding the reverse_moves method. 


```python
def reverse_moves(self, is_modify=False):
     action = super(
           AccountMoveReversal, self.with_context(force_copy_stock_moves=True)
     ).reverse_moves()
``` 

By not passing the is_modify=is_modify parameter, this prevents proper functioning.

**Comment by ferran-S73** [comment]
> There seems to be an error in the way of overriding the reverse_moves method.
> 
> ```python
> def reverse_moves(self, is_modify=False):
>      action = super(
>            AccountMoveReversal, self.with_context(force_copy_stock_moves=True)
>      ).reverse_moves()
> ```
> 
> By not passing the is_modify=is_modify parameter, this prevents proper functioning.

Fixed in 
- https://github.com/OCA/stock-logistics-workflow/pull/1703

@lethuthao2403 @gurneyalex could you review?

**Pull request merged**
