### PR TITLE
[12.0][FIX] stock_return_request: Fix tests

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa
ping @carlosdauden @CarlosRoca13

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Travis fails due to stock_picking_package_preparation_line module..

**Review by carlosdauden — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you explain a bit the previous error and why it was failing?

**Comment by sergio-teruel** [comment]
Yes!!
This PR remove the use of non existing field qty_done in stock.move model.
The action_assign method invoke is not necessary.
This tests creates stock move lines and if user invokes action_assign can unreserve moves.

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by sergio-teruel** [comment]
Travis is red due to stock_picking_package_preparation_line module

**Comment by pedrobaeza** [comment]
OK, is this fix needed for our integration tests?

**Comment by sergio-teruel** [comment]
For v12.0 no... was needed for v13.0

**Comment by pedrobaeza** [comment]
OK, let's keep then to see if authors of the other module fix their tests.

**Comment by dreispt** [comment]
Travis is red

**Comment by rousseldenis** [comment]
@sergio-teruel Could you rebase ?

**Pull request closed without merging**
