### PR TITLE
[16.0][MIG] stock_picking_invoice_link: Migration to 16.0

### PR DESCRIPTION
**Pull request by JoelZilli**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@JoelZilli Thanks for this. Could you fix tests ?

**Comment by JoelZilli** [comment]
@rousseldenis No problem, yes i'm working on the tests.

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review LGTM

**Comment by augusto-weiss** [comment]
@JoelZilli i added a commit fixing test

**Review by rvalyi — APPROVED** [review]
tested with success on Runboat (you need to install the sale management module to get the sales menu). It also includes the latest commits to deal with refunds, so all good for me! Thanks for the work!

**Comment by pedrobaeza** [comment]
@JoelZilli @augusto-weiss I'm wondering why did you remove it this code:

https://github.com/OCA/stock-logistics-workflow/pull/1154/commits/4305494985706fd482dfefc56c226b719622789f#diff-ce669341e9570e3e12e9f5eebf9a82ca87535bab7d791024ef7cdf6932427144L53

**Pull request merged**
