### PR TITLE
[14.0][MIG] product_expiry_simple

### PR DESCRIPTION
**Pull request by alexis-via**
Migration from v12 (PR https://github.com/OCA/stock-logistics-workflow/pull/532) to v14.

### CODE REVIEW

**Comment by alexis-via** [comment]
I added a nice warning banner on pickings:

warn_expiry_v14

**Comment by rousseldenis** [comment]
@alexis-via This has been closed and can't be reopened. Could you do a new PR ?

**Comment by bealdav** [comment]
Hi @alexis-via I'me interesting in opens again this PR. Could you proceed ?

**Comment by bealdav** [comment]
see https://github.com/OCA/stock-logistics-workflow/pull/1271

**Pull request closed without merging**
