### PR TITLE
[14.0][MIG] stock_quant_package_dimension

### PR DESCRIPTION
**Pull request by hparfr**

### CODE REVIEW

**Comment by hparfr** [comment]
@grindtildeath

**Review by bguillot — APPROVED** [review]
Tested LGTM

**Comment by rousseldenis** [comment]
Depends on : https://github.com/OCA/product-attribute/pull/736

**Comment by hparfr** [comment]
ping @kev-roche @sebastienbeau

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)

**Pull request merged**
