### PR TITLE
[10.0][FIX]keep original sequence when creating backorders

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Current behavior: _reset_sequence method is called and the sequence of the backorder is not respected.

Desired behavior: backorder sequence is respected

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@aheficent Maybe a test to highlight that process should have been cool.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
@aheficent please, rebase to greenify it.

**Comment by AaronHForgeFlow** [comment]
Ping @lreficent

**Pull request merged**
