### PR TITLE
[ADD][stock_items_lend] - Module to manage products lend.

### PR DESCRIPTION
**Pull request by ougc27**
Hello @pedrobaeza 

This new module add a stock location route to manage a products lend for example the
workshop tools.

I hope this module would be functional to be merged.
Thanks & Regards!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
And which is the difference with https://github.com/OCA/stock-logistics-workflow/tree/9.0/stock_deposit?

**Comment by rousseldenis** [comment]
@ougc27

**Comment by rousseldenis** [comment]
@ougc27

**Comment by rousseldenis** [comment]
Closing this as no answer. Please feel free to reopen it if you want to attend comments or finish the work.

**Pull request closed without merging**
