### PR TITLE
[13.0][MIG] stock_picking_filter_lot

### PR DESCRIPTION
**Pull request by newtratip**
I changed the location for make sure quantity > 0
Selection_333

Is there any concern for change this ?

### CODE REVIEW

**Comment by rousseldenis** [comment]
> I changed the location for make sure quantity > 0
> Selection_333
> 
> Is there any concern for change this ?

I think this is ok.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by lk-eska** [comment]
> > I changed the location for make sure quantity > 0
> > Selection_333
> > Is there any concern for change this ?
> 
> I think this is ok.

No it isn't ok.

Reason 1: It will not compute when quantity is changed positive to negative (when it becomes zero it is ok since it will delete the quant and trigger compute) 

Reason 2: This formula will eliminate Vendor location to be in locations (because the quantity is negative), thus it will not possible to buy the same product with the same lot number.

**Pull request merged**
