### PR TITLE
[12.0][FIX] stock_picking_mass_action: Error mass picking transfer mixing

### PR DESCRIPTION
**Pull request by carlosdauden**
complete and partial pickings

@Tecnativa TT22115

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
A test for avoiding regressions would be good

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@carlosdauden Do you plan to add test as suggested ?

**Comment by carlosdauden** [comment]
Yes, I plan yo add test, don't merge yet.

**Comment by carlosdauden** [comment]
Test added

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by carlosdauden** [comment]
Travis :green_apple:

**Pull request merged**
