### PR TITLE
[12.0][IMP] stock_picking_batch_extended: Add followers, attachments, chatt…

### PR DESCRIPTION
**Pull request by carlosdauden**
…er and activities

@Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@carlosdauden Travis is red. Can you please take also the opportunity to change the maintainers for being real GitHub users?

**Review by pedrobaeza — APPROVED** [review]

**Review by manuelcalerosolis — COMMENTED** [review]
I think we should include the file USAGE.rst to explain that we should use this module, it must contain something like this.

To configure this module, you need to:

* Goto (Inventory > Configuration > and select "Use OCA approach to validate Picking Batch")

**Review by manuelcalerosolis — APPROVED** [review]
Only include USAGE.rst

**Comment by pedrobaeza** [comment]
That would be CONFIGURE.rst, not USAGE.rst. Any way, let's merge it and let that as an improvement not directly related with this PR.

/ocabot merge minor

Please forward port it to v13 as well.

**Pull request merged**
