### PR TITLE
[15.0][IMP] stock_owner_restriction: Add hook to allow to modify the owner behaviour by other modules when gather quants

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT48552

ping @carlosdauden @chienandalu

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]
Add module name in title

**Comment by sergio-teruel** [comment]
Done!!

**Comment by sergio-teruel** [comment]
Wiating to merge this PR https://github.com/OCA/stock-logistics-workflow/pull/1385 to port to v16

**Comment by pedrobaeza** [comment]
I see that PR red

**Pull request merged**
