### PR TITLE
[15.0] mig stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by robin5210**

### CODE REVIEW

**Comment by celm1990** [comment]
migration is in progress in PR https://github.com/OCA/stock-logistics-workflow/pull/951 you reviews and comments are welcome

**Comment by rousseldenis** [comment]
@robin5210 Could you close this?

**Comment by celm1990** [comment]
@robin5210  PR is here https://github.com/OCA/stock-logistics-workflow/pull/1006 you reviews and comments are welcome

**Comment by rousseldenis** [comment]
As there is no answer and no activity, closing this in favor of #1006

**Pull request closed without merging**
