### PR TITLE
[17.0][FW] stock_restrict_lot: Multiple ports from 16.0

### PR DESCRIPTION
**Pull request by sebalix**
Same PR than #1714 

Port of the following PRs from 16.0 to 17.0:
- #1179
- #1443
- #1671

### CODE REVIEW

**Comment by sebalix** [comment]
Commits adapted to fit the new Odoo 17.0 code base and API.

**Review by florian-dacosta — APPROVED** [review]
Looks good too, thanks

**Review by petrus-v — APPROVED** [review]
LGTM thanks taking care to forward such commits

**Pull request merged**
