### PR TITLE
[13.0][MIG] stock_move_quick_lot

### PR DESCRIPTION
**Pull request by ps-tubtim**

### CODE REVIEW

**Review by joao-p-marques — APPROVED** [review]
Code and functional review :+1: 

TT22090

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@ps-tubtim can you please rebase and include the changes of the XML in the pre-commit commit?

**Comment by ps-tubtim** [comment]
@joao-p-marques Thank you for your review.
@pedrobaeza Thank you for your review and suggestion. I already updated the XML with the pre-commit.

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by joao-p-marques** [comment]
It seems like Travis is getting some errors when installing `prettier` in pre-commit. I am getting the same error in other repos as well.

**Pull request merged**
