### PR TITLE
[17.0][MIG] delivery_procurement_group_carrier: Migration to 17.0 

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 154101

@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/stock-logistics-workflow/issues/1421

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
Functionally working, tested in runboat

**Review by lbarry-apsl — APPROVED** [review]
LGTM, It works well

**Comment by peluko00** [comment]
Ready for merge @rousseldenis ?

**Review by sebalix — APPROVED** [review]

**Pull request merged**
