### PR TITLE
Wizard on dispatchs allowing to start a whole selection

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
:+1:

**Comment by rdeheele** [comment]
:+1:

**Comment by gurneyalex** [comment]
@guewen one small typo fix needed and I merge

**Comment by guewen** [comment]
Fixed and rebased

**Comment by guewen** [comment]
Red due to pep8 in other modules

```
./picking_line_description/stock_move.py:40:26: E241 multiple spaces after ','
./product_customer_code_picking/stock_picking.py:41:21: E123 closing bracket does not match indentation of opening bracket's line
./picking_dispatch/report/dispatch_report.py:95:37: E241 multiple spaces after ','
```

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
