### PR TITLE
[14.0][MIG] stock_owner_restriction: Migration to 14.0

### PR DESCRIPTION
**Pull request by ferran-S73**
Standard migration from 13.0 to 14.0.

Updates [this PR](https://github.com/OCA/stock-logistics-workflow/pull/731).

### CODE REVIEW

**Comment by ferran-S73** [comment]
@sergio-teruel @rousseldenis @chienandalu could any of you review this PR please?

**Comment by ferran-S73** [comment]
@rousseldenis I've rebased the branch manually

**Review by rousseldenis — APPROVED** [review]

**Review by fuentes73 — APPROVED** [review]

**Pull request merged**
