### PR TITLE
[16.0][MIG] stock_picking_purchase_propagate: Migration to 16.0

### PR DESCRIPTION
**Pull request by lehoangan**
Depend on:
[#1806](https://github.com/OCA/purchase-workflow/pull/1806)

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review. LGTM.

Note: I would have split the stock.move code in a separate module

**Comment by StephaneMangin** [comment]
For the PR dependency, please take in account this comment https://github.com/OCA/edi/pull/724#issuecomment-1461765822

**Review by hugo-cordoba — APPROVED** [review]

**Comment by hugo-cordoba** [comment]
LGTM

**Comment by lehoangan** [comment]
> For the PR dependency, please take in account this comment [OCA/edi#724 (comment)](https://github.com/OCA/edi/pull/724#issuecomment-1461765822)

plz check [[DON'T MERGE] test-requirements.txt](https://github.com/OCA/stock-logistics-workflow/pull/1253/commits/969c83bd0abe913de0719924d5eb435511801d68)

**Comment by rousseldenis** [comment]
@lehoangan To help reviewers, please include your dependencies in the PR description (that would lead them to those Prs and review them too). Thanks

**Comment by lehoangan** [comment]
> 

I added it

**Review by yung-wang — COMMENTED** [review]
Looking good. Works fine

**Pull request closed without merging**
