### PR TITLE
[10.0][ENH] stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Add `post_init_hook` to attach existing invoices to existing pickings when installing the module

### CODE REVIEW

**Review by AdriaGForgeFlow — COMMENTED** [review]
Nitpicking: pre_init_hook should be placed in file 'hooks.py' according to OCA guidelines (https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#installation-hooks)

**Comment by rousseldenis** [comment]
@aheficent oups. Seems you took some unrelevant commits

**Comment by rousseldenis** [comment]
> Nitpicking: pre_init_hook should be placed in file 'hooks.py' according to OCA guidelines (https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#installation-hooks)

@aheficent

**Comment by rousseldenis** [comment]
@aheficent I think this is red

**Comment by AyoubZahid** [comment]
for Odoo v10, The hook function must be defined inside the init file otherwise it doesn't work.

**Comment by rousseldenis** [comment]
@aheficent

**Pull request closed without merging**
