### PR TITLE
[17.0][MIG] stock_move_line_reference_link

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM

**Review by CarlosVForgeFlow — APPROVED** [review]
LGTM

**Review by JordiMForgeFlow — APPROVED** [review]
code + functional review

**Review by LoisRForgeFlow — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
