### PR TITLE
[14.0][FIX] stock_picking_show_return fix tests

### PR DESCRIPTION
**Pull request by dzungtran89**
This is a known issue fixed in this PR https://github.com/OCA/stock-logistics-workflow/pull/886

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please cherry-pick the commit instead for not losing attribution.

**Comment by dzungtran89** [comment]
thx @pedrobaeza , I'll update it

**Comment by pedrobaeza** [comment]
Please squash both commits into one, as the second one wasn't needed if the conflict resolution on the first one was correct.

**Review by simahawk — APPROVED** [review]
LG. Fine for you @pedrobaeza ?

**Pull request merged**
