### PR TITLE
[FIX] flake8 error:  E305 expected 2 blank lines after class or function definition

### PR DESCRIPTION
**Pull request by tafaRU**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by tafaRU** [comment]
speedy @pedrobaeza :wink:

**Comment by hurrinico** [comment]
:+1: IMHO

**Comment by pedrobaeza** [comment]
hehe, for what is needed :wink:

**Review by eLBati — APPROVED** [review]

**Comment by tafaRU** [comment]
@pedrobaeza please merge it!
Thank you in advance.

**Pull request merged**
