### PR TITLE
8.0 stock picking partial invoicing

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Substitutes https://github.com/OCA/stock-logistics-workflow/pull/192

### CODE REVIEW

**Comment by gurneyalex** [comment]
I'm checking travis on a rebased version of this PR, since the errors seem to be unrelated to the PR.

**Comment by gurneyalex** [comment]
@jbeficent Could you rebase your PR? I've done this on a personal branch and it looks like the tests are running fine on odoo/odoo but fail on OCA/OCB (see https://travis-ci.org/gurneyalex/stock-logistics-workflow/jobs/138287842#L1238)

It looks like a very nice module which I'd love to see in the OCA. Thanks for your help in solving this.

**Comment by Cedric-Pigeon** [comment]
@jbeficent Do you plan to fix this one ?

**Comment by rousseldenis** [comment]
@jbeficent

**Comment by rousseldenis** [comment]
Closing this as no answer. Feel free to repoen it

**Pull request closed without merging**
