### PR TITLE
[15.0][MIG] product_cost_price_avco_sync: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36494

Migrated from https://github.com/OCA/stock-logistics-workflow/pull/802

ping @carlosdauden @sergio-teruel

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
ping @pedrobaeza @sergio-teruel

**Comment by pedrobaeza** [comment]
I'm doing modifications in 13.0 now, so this will be affected. I will ping you when ready.

**Comment by CarlosRoca13** [comment]
:+1:

**Review by rafaelbn — APPROVED** [review]
LGTM 👍

**Comment by CarlosRoca13** [comment]
@rafaelbn I think we should have waited until we added the latest changes to 13.0 to merge this PR :sweat_smile: 

I will add them by new PRs on 14.0 and 15.0, when I have a chance

**Pull request merged**
