### PR TITLE
[IMP] stock_picking_invoice_link: add a button to open invoices

### PR DESCRIPTION
**Pull request by sebalix**
Forward port of #337 
@tafaRU

### CODE REVIEW

**Comment by sebalix** [comment]
Tests fail on `stock_account_deposit` (related to `stock_no_negative`).
WIP regarding `stock_picking_invoice_link`.

**Comment by sebalix** [comment]
@tafaRU Fixed, ready for review.

**Comment by pedrobaeza** [comment]
Please check https://github.com/OCA/stock-logistics-workflow/pull/296 that fixes also the behavior.

**Comment by pedrobaeza** [comment]
You need to rebase and resolve conflicts.

**Comment by sebalix** [comment]
@pedrobaeza done
Tests now fails on `stock_picking_invoice_link` due to `stock_no_negative`. Don't know what is the best approach to fix this.

**Comment by pedrobaeza** [comment]
The idea should be that stock_no_negative shouldn't be activated if it's in test mode and you are not testing the module itself. Something similar has been done on https://github.com/OCA/bank-payment/blob/c5b093fb5ef1df31a699e49c90db646db115b44a/account_payment_transfer_reconcile_batch/models/payment_order.py#L28 (but there's an extra condition here for reusing the same method for both with and without connector).

**Comment by MiquelRForgeFlow** [comment]
@sebalix , delete last commit and rebase 😉

**Comment by sebalix** [comment]
@pedrobaeza @mreficent done, all is green now, thank you

**Review by pedrobaeza — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
