### PR TITLE
[10.0][MIG] stock_pack_operation_auto_fill: Migration to 10.0

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
#360

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review + tested on runbot.

**Review by LoisRForgeFlow — APPROVED** [review]
Tested, LGTM :+1:

**Review by etobella — APPROVED** [review]
Tested on RunBot

**Comment by MiquelRForgeFlow** [comment]
Why are there two Travis? :thinking:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Tested on runbot. Works great!

**Review by zakiuu — APPROVED** [review]

**Pull request merged**
