### PR TITLE
[10.0][FIX] stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Adapt to odoo/odoo@b1a373c.

Sigh... 😒

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@lreficent @pedrobaeza

**Comment by pedrobaeza** [comment]
Maybe we should change the approach for not checking the returning value, but the state of the data?

**Comment by MiquelRForgeFlow** [comment]
Well, but I prefer my lazy approach. I don't think Odoo will change again this 😂😤

**Comment by MiquelRForgeFlow** [comment]
:green_apple: @pedrobaeza ASAP

**Pull request merged**
