### PR TITLE
Create requirements.txt

### PR DESCRIPTION
**Pull request by ovnicraft**
migrations use library

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]
(Red Travis is unrelated)

**Comment by pedrobaeza** [comment]
This is not needed at all, as in Travis openupgradelib is not needed, and for your system, you need to have it, but not for this specific repo.

**Comment by ovnicraft** [comment]
@pedrobaeza so as external library used on modules, must not declared on requirements ?

**Comment by pedrobaeza** [comment]
It's only used for migrations, not for regular operation, so it's not needed to be put on requirements.txt.

**Pull request closed without merging**
