### PR TITLE
[14.0][MIG] stock_picking_show_backorder

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
This module provide a new field on stock pickings, allowing to see the
backorders associated to a picking.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional review Ok. Pending to fix test.

**Comment by rousseldenis** [comment]
@JuanyDForgeflow Please do a new PR for the fix as this problem breaks 14.0 branch. I'll merge it quickly. Thanks

**Comment by AaronHForgeFlow** [comment]
@rousseldenis I extracted the last commit here: https://github.com/OCA/stock-logistics-workflow/pull/997 :)

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Review by LoisRForgeFlow — APPROVED** [review]

**Pull request merged**
