### PR TITLE
[12.0][ADD] stock_picking_filter_lot: add logic to filter by lots in stock scrap

### PR DESCRIPTION
**Pull request by alan196**
This PR logic to show only lots that can be scrapped

### CODE REVIEW

**Review by lmgr0312 — APPROVED** [review]
I tested functionally this module and it works...

**Review by Tino480 — APPROVED** [review]
Tried changes and they worked

**Review by rousseldenis — APPROVED** [review]
Code review. Makes sense

**Comment by alan196** [comment]
@rousseldenis  The error in the test is not related to this module

**Comment by rousseldenis** [comment]
Could you rebase?

**Comment by alan196** [comment]
@rousseldenis  I rebased before my last message 👍 everything is up-to-date

**Comment by rousseldenis** [comment]
Ok, trying one more time.

/ocabot merge minor

**Pull request merged**
