### PR TITLE
[14.0][FIX] stock_picking_auto_create_lot: create new serial number for lots

### PR DESCRIPTION
**Pull request by dessanhemrayev**
This bug was discovered while working with this module #1375

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dessanhemrayev Same comment as in https://github.com/OCA/stock-logistics-workflow/pull/1565

**Review by geomer198 — CHANGES_REQUESTED** [review]
Please add message for each assertion.

**Review by geomer198 — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@rousseldenis good for you?

**Comment by dessanhemrayev** [comment]
@rousseldenis  check please)

**Review by rousseldenis — APPROVED** [review]
Seems fair

**Pull request merged**
