### PR TITLE
[16.0][MIG] stock_picking_warn_message: Migration to 16.0

### PR DESCRIPTION
**Pull request by dhx**
Standard migration

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Hi @dhx could you rebase, please?

**Comment by dhx** [comment]
> Hi @dhx could you rebase, please?

Sure @HaraldPanten ! A review is most welcome :)

**Review by HaraldPanten — APPROVED** [review]
Functional review in runboat. LGTM. 👍

@rousseldenis @pedrobaeza

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Oops. Mine aborted.

**Pull request merged**
