### PR TITLE
Create test.yml

### PR DESCRIPTION
**Pull request by MarkHarris21**

### CODE REVIEW

**Comment by effigies** [comment]
@simahawk  Cryptocurrency miner. Please cancel actions, report user and block.

**Comment by effigies** [comment]
cc @pedrobaeza

**Comment by simahawk** [comment]
@effigies user blocked and reported. Thanks for the ping! :)
CC @sbidoul @bguillot

**Comment by sbidoul** [comment]
I also cancelled the pending workflows. I suspect there are others because the pre-commit jobs on 14.0 are stuck.

**Pull request closed without merging**
