### PR TITLE
[12.0] NEW stock_picking_filter_product: 

### PR DESCRIPTION
**Pull request by alan196**
A new module that allows filtering products shown in pickings and stock scrap to select only available products in origin location.

This module is based on the logic of stock_picking_filter_lot module.

### CODE REVIEW

**Review by lmgr0312 — APPROVED** [review]
LGTM!

**Comment by Tino480** [comment]
Looks and works as described

**Review by Tino480 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@alan196 Thanks for your contribution. I don't really like the module name as it does not reflect what it does on a functional point of view. Could you enhance a little bit ?

**Comment by alan196** [comment]
🤔 What do you think of 

- stock_filter_product_by_location
- stock_filter_product_by_source_location
- stock_show_products_source_location

@rousseldenis

**Pull request merged**
