### PR TITLE
[IMP] sale_global_stock_route: prevent to update route_id on confirme…

### PR DESCRIPTION
**Pull request by bealdav**
…d sales

@cvinh @carlosdauden @CarlosRoca13

### CODE REVIEW

**Review by cvinh — APPROVED** [review]
Even if it's still draft, I understand what you did and of course I'm approving

**Review by carlosdauden — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by rousseldenis** [comment]
Mmmh, I understand the problem you have but:

- In Odoo core, the route_id field on sale order line is readonly in "done" and "cancel"

That's why I think the best is to mimic the same states.

**Comment by bealdav** [comment]
@rousseldenis Thanks for your suggestion.
But readonly is only in the view then method in current module can change the field isn't it ?

**Comment by bealdav** [comment]
And on the user side, it can let think we can update the flow whereas we should not. Then it's error prone or at least a source of misunderstood isn't it ?

**Comment by cvinh** [comment]
> Mmmh, I understand the problem you have but:
> 
> * In Odoo core, the route_id field on sale order line is readonly in "done" and "cancel"
> 
> That's why I think the best is to mimic the same states.

Well IMHO sometimes, Odoo's way is not the best... but sometimes it is... 
I prefer sale, done... if it's cancelled then why would it be forbidden to change it...
I vote for @bealdav way

**Comment by bealdav** [comment]
@rousseldenis maybe I misunderstood your message but my commit also makes field readonly when state in done/cancel, then that's the odoo way ? I missed something ?

**Comment by cvinh** [comment]
> @rousseldenis maybe I misunderstood your message but my commit also makes field readonly when state in done/cancel, then that's the odoo way ? I missed something ?

@bealdav you did
attrs="{'readonly': [('state', 'in', ('sale', 'done'))
and I vote for you

**Comment by rousseldenis** [comment]
> @rousseldenis maybe I misunderstood your message but my commit also makes field readonly when state in done/cancel, then that's the odoo way ? I missed something ?

In fact, that's the behaviour for the lines in `sale` state, you can still add lines with a route (e.g. : for MTO).

Here, the field is global, so, it can be good to protect `sale`state too.

But for the `cancel`state, you should not be able to change something too. So, I would have added that state

**Comment by bealdav** [comment]
Sorry I misread states, really sorry  :-(

Everybody is OK for  `'readonly': [('state', 'in', ('sale', 'done', 'cancel'))]` ?

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
