### PR TITLE
[16.0][MIG] stock_landed_costs_delivery: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v16
- Squash administrative commits
- Depends on https://github.com/OCA/delivery-carrier/pull/755/
- Tests are failed because this PR, depends on: https://github.com/OCA/delivery-carrier/pull/781

@Tecnativa
TT47862

@pedrobaeza @victoralmau

### CODE REVIEW

**Review by victoralmau — APPROVED** [review]

**Comment by carolinafernandez-tecnativa** [comment]
ping @pedrobaeza

**Review by christian-ramos-tecnativa — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Comment by pedrobaeza** [comment]
Greenified in #1605 

/ocabot merge nobump

**Pull request merged**
