### PR TITLE
[16.0][MIG] stock_valuation_layer_usage: Migration to 16.0

### PR DESCRIPTION
**Pull request by EvaSForgeFlow**
Depends on: #1323

### CODE REVIEW

**Comment by rousseldenis** [comment]
@EvaSForgeFlow Thanks for  this. You can also embed your dependency here to make tests running and having a runboat instance for functional testing.

https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@JordiBForgeFlow Some dependencies are not yet merged

**Comment by rousseldenis** [comment]
@EvaSForgeFlow Could you remove the test-requirements commit as #1323 is merged ?

**Pull request merged**
