### PR TITLE
[14.0][FIX] stock_split_picking

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**
previously, records without any done quantities were sent to the new picking

### CODE REVIEW

**Comment by rousseldenis** [comment]
@xavier-bouquiaux @Guenzn Could you try to synchronize and find a unique solution for this same problem ?

https://github.com/OCA/stock-logistics-workflow/pull/961

**Comment by xavier-bouquiaux** [comment]
@rousseldenis 
the test has been added, as said i the commit message : 
add a test to validate that if i split a picking with 3 lines
2 not done
1 partially done
the resulting backorder will contain
the 2 not done
the rest of the partially done

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@xavier-bouquiaux Could you squash your commits ?

**Comment by Guenzn** [comment]
@xavier-bouquiaux is it possible to try this code on runbot?

**Comment by rousseldenis** [comment]
> @xavier-bouquiaux is it possible to try this code on runbot?

You can always. Click on 'details' on runbot build here under.

**Comment by rousseldenis** [comment]
> > @xavier-bouquiaux is it possible to try this code on runbot?
> 
> You can always. Click on 'details' on runbot build here under.

Or better, on runboat

**Comment by Guenzn** [comment]
> > > @xavier-bouquiaux is it possible to try this code on runbot?
> > 
> > 
> > You can always. Click on 'details' on runbot build here under.
> 
> Or better, on runboat
THX for this information! As i said, this fix will not cover my scenario and the bug i described and i had fixed with pull request #961 will exists furthermore. Please see my new movie below i created 5 minutes before on your build.

https://user-images.githubusercontent.com/24382867/152751116-04ac5fa3-a147-4965-a413-5e6689bb6063.mp4

**Pull request closed without merging**
