### PR TITLE
14.0 mig stock picking whole scrap

### PR DESCRIPTION
**Pull request by cbssolutions**

### CODE REVIEW

**Review by hailangvn — APPROVED** [review]
LGTM. Thanks for the work. It will be perfect if...
* Commit title is changed to `[MIG] stock_picking_whole_scrap: Migration to v14.0 with expired lots`
* PR title is changed to `[14.0][MIG] stock_picking_whole_scrap: Migration to 14.0` so that we can easily search in [Pull requests](https://github.com/OCA/stock-logistics-workflow/pulls?q=is%3Apr+is%3Aopen+stock_picking_whole_scrap) view. As you can see from the link, this PR is missing.
* Fixup [last commit](https://github.com/OCA/stock-logistics-workflow/pull/870/commits/8ebfe198af7bd574c9ee8bbf145865b6a3623068) with [previous commit](https://github.com/OCA/stock-logistics-workflow/pull/870/commits/8cbe8d8545b63b64a832841874c28ecd4875e712).
* Comment in [tracking issue](https://github.com/OCA/stock-logistics-workflow/issues/708). Better if comment as `* stock_picking_whole_scrap: WIP` before doing migration so that other developer doesn't do the same work.

**Comment by rousseldenis** [comment]
@alexteodor

**Comment by rousseldenis** [comment]
@cbssolutions

**Pull request closed without merging**
