### PR TITLE
[MERGE] picking_dispatch merge V7 -> V8

### PR DESCRIPTION
**Pull request by cyrilgdn**

### CODE REVIEW

**Comment by gurneyalex** [comment]
@cyrilgdn can you check the warning in the runbot logs?

**Comment by gurneyalex** [comment]
@cyrilgdn please solve the conflicts.

**Comment by cyrilgdn** [comment]
@gurneyalex Rebased.

**Comment by gurneyalex** [comment]
:+1:

**Comment by ehahouimohssine** [comment]
:+1:

**Pull request merged**
