### PR TITLE
 [12.0][MIG] stock_picking_sale_order_link: Migration to 12.0

### PR DESCRIPTION
**Pull request by hegenator**
Migration of stock_picking_sale_order_link to 12.0

### CODE REVIEW

**Comment by hegenator** [comment]
I have in fact signed the CLA, but forgot I only had my personal email in my github profile so I assume that is why the CLAbot didn't find my CLA.

**Comment by pedrobaeza** [comment]
Yeah, that's it. You have to commit with that email address, or sign the CLA for the other email.

**Comment by pedrobaeza** [comment]
Sorry, actually, that's not the problem, as CLA bot checks by github login, not email. The problem is with some other commits. I will check further.

**Comment by hegenator** [comment]
I also found out that I might have originally sent the signed individual CLA email but forgotten to actually attach the signed document 🤦‍♂️  I've just resent the document.

**Comment by pedrobaeza** [comment]
I have opened an issue about CLAbot error: https://github.com/OCA/maintainer-tools/issues/394

**Comment by gurneyalex** [comment]
fixed on the clabot.

**Review by rousseldenis — APPROVED** [review]

**Review by tbaden — APPROVED** [review]

**Pull request merged**
