### PR TITLE
[17.0][MIG] purchase_stock_picking_invoice_link

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:
- https://github.com/OCA/stock-logistics-workflow/pull/1712

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Please rebase.

**Comment by JasminSForgeFlow** [comment]
> Please rebase.

Done

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM

**Review by sebalix — APPROVED** [review]

**Pull request merged**
