### PR TITLE
Add messages to product and stock picking when date is computed

### PR DESCRIPTION
**Pull request by mdietrichc2c**

### CODE REVIEW

**Comment by gurneyalex** [comment]
#38 is expected to make the 7.0 branch clean, which should fix the build of this PR.

**Comment by gurneyalex** [comment]
I requested a rebuild

**Comment by mdietrichc2c** [comment]
Thanks @gurneyalex

**Comment by eLBati** [comment]
:+1:

**Comment by pedrobaeza** [comment]
You should recreate pot file.

**Comment by jgrandguillaume** [comment]
:+1:  after the .pot regenerated

**Comment by mdietrichc2c** [comment]
Sorry, missed the comment; .po file is now added.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1: just pot file to rename to .pot instead of .po

**Comment by yvaucher** [comment]
Thanks

**Pull request merged**
