### PR TITLE
[MIG][10.0] stock_picking_show_returns

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This doesn't work either. The problem is that you are taking the number in plural, but the module was renamed a long time ago to singular: `stock_picking_show_return`

**Comment by pedrobaeza** [comment]
And you don't need to close PRs. You just need to reuse the same branch name.

**Comment by fmdl** [comment]
I am not change the name of module, it is with "s", please see below : https://github.com/OCA/stock-logistics-workflow/tree/10.0/stock_picking_show_returns

regards

**Comment by pedrobaeza** [comment]
In v8 and v9 the name is without s. That's why you don't import the commit history:

https://github.com/OCA/stock-logistics-workflow/tree/8.0/stock_picking_show_return
https://github.com/OCA/stock-logistics-workflow/tree/9.0/stock_picking_show_return

**Comment by pedrobaeza** [comment]
The v9 version is going to work as is in v10.

**Pull request closed without merging**
