### PR TITLE
[FIX] stock_split_picking: Fixed "split" when spliting move lines in stock.picking

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
Superseed of #185

### CODE REVIEW

**Comment by hbrunn** [comment]
:+1:

**Comment by yvaucher** [comment]
I tested on runbot and I still get strange results when having 2 lines on my picking.

When trying:
I add 400 M-Wir to my inventory
I add 50 Ice creams to my inventory
I create a picking with 50 M-Wir and 200 Ice creams
I mark as todo
As I have 50 available for each
I want to split 50 M-Wir and 50 Ice creams (all what is available) to be able to send them which is what the wizard propose me by default.

I end up with:
- a picking with 50 Ice creams (available) which can be transfered
- a picking with 50 M-Wir (available) and 150 Ice creams (unavailable) (M-Wir were not pushed in the right picking)

Would this be an issue with another module ?

**Comment by hbrunn** [comment]
So the amounts are correct (that's what this PR is supposed to fix, so: yay!), but you'd expect a different distribution? I think that needs to be addresses as a feature of the splitting wizard.

**Comment by yvaucher** [comment]
@hbrunn The amounts are correct in total but not in the right picking. It is strange that selecting in the wizard.
- 20/100 product A 
- 100/100 product B

gives me a picking
- 80/100 product A
- 100/100 product B

And a second picking with
- 20/100 product A

Still hard for the user to predict what the wizard will do.

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by yvaucher** [comment]
@Cedric-Pigeon That was 1 year ago but I'm still concerned about my last comment. Did you take it into account ?

**Comment by Cedric-Pigeon** [comment]
@yvaucher No I did not test it. So far I am not using that module anymore as I am currently migrating my project to 10.0. Perhaps the best is to open an issue to keep track.

**Pull request merged**
