### PR TITLE
[MIG] stock_lot_scrap: Migration to 10.0

### PR DESCRIPTION
**Pull request by chienandalu**
Scrap Complete Lot
==================

This module adds a button in *Production Lot/Serial Number* view form to
*Scrap* all quants contained.

cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
v10 includes now a new object stock.scrap that you have to fill and call the corresponding method (do_scrap) instead of doing this manually. Please change the flow to accommodate it to this new feature.

**Comment by pedrobaeza** [comment]
Does this the scrap itself or only redirects to the view of scraps?

**Comment by chienandalu** [comment]
It takes every quant in the lot and scraps it. The `create` method in `stock.scrap` has a call to the `do_scrap` method.

**Comment by pedrobaeza** [comment]
OK, cool. I'll try when runbot finishes.

**Comment by rousseldenis** [comment]
IMHO, the idea should be to improve stock.scrap form to fill in the quantity to scrap as in the standard scrap form :

- You select the product, and automatically the available lots are selectable
- You cannot enter quantity superior to the available lot quantity for the location you scrap

The process introduced by this module (through production.lot form) should stay in addition.

@chienandalu What do you think about ?

image

**Comment by pedrobaeza** [comment]
Well, the idea is good, but we don't plan to work more on this. We can put it on the roadmap any way. What do you think?

**Comment by rousseldenis** [comment]
@pedrobaeza Ok, we should try not to reinvent the wheel (even if stock.scrap is new and Odoo makes us sometimes schyzophrenic on changes between versions...)

**Review by pedrobaeza — APPROVED** [review]

**Comment by chienandalu** [comment]
@rousseldenis But actually I've adapted the migration to the new scrap model and its methods which should be the focus for the migration, I think.

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM. Adapting the module to `stock.scrap` seems enough to me for the migration.

**Comment by rousseldenis** [comment]
@chienandalu I've just tested it and I think the Scrap button should have a 'Are you sure?' confirmation as the whole quantity is directly scraped. What do you think ?

**Comment by chienandalu** [comment]
@rousseldenis I added the confirmation dialog although I had to move the button to the button box and avoid all the dynamic header part... I'm not sure it's fine like this.

**Comment by pedrobaeza** [comment]
@chienandalu for having a confirmation dialog you just need to add an attribute `confirm` and write the text you want to put :scream: Example: https://github.com/odoo/odoo/blob/d6d901c7bc23c7aaafd09c2abccfbe6a7c963b70/addons/account_voucher/views/account_voucher_views.xml#L220

Please undo last commit and do that.

**Comment by chienandalu** [comment]
Oh my... :flushed: I guess I learnt it the hard way. Changed.

**Pull request merged**
