### PR TITLE
[15.0][MIG] stock_picking_line_sequence

### PR DESCRIPTION
**Pull request by slominchar**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@slominchar Thanks for this. Could you check tests ?

**Comment by JuanyDForgeflow** [comment]
@slominchar please run pre-commit

**Comment by rousseldenis** [comment]
@slominchar Thanks for this. Could you squash all fixing commits in the migration one ?

**Comment by LoisRForgeFlow** [comment]
@slominchar could you attend @rousseldenis comment and squash migration changes/fixes in one commit?

**Comment by LoisRForgeFlow** [comment]
Closed in favor of https://github.com/OCA/stock-logistics-workflow/pull/1211.

**Pull request closed without merging**
