### PR TITLE
[10.0] stock_auto_move: forward port PR 359 from V9

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
Forward port of #359

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@rousseldenis

**Review by Jortolsa-S73 — APPROVED** [review]

**Review by fuentes73 — APPROVED** [review]

**Comment by rousseldenis** [comment]
@Cedric-Pigeon I think you should take the commit history from v9.

**Comment by Jortolsa-S73** [comment]
Functional and technical review, keep in mind #364 to avoid the automatic procurement group problem.

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Comment by rousseldenis** [comment]
@Cedric-Pigeon Do you plan to finish this or could I close ?

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Comment by rousseldenis** [comment]
Closing as old. Please feel free to reopen if needed.

**Pull request closed without merging**
