### PR TITLE
Updated from template - Switch to Github actions

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Detected licenses issues:

- delivery_total_weight_from_packaging : @sebalix Your module is LGPL and depends on AGPL one. It is forbidden. What do you want for this ?

Thanks for your answer

**Comment by rousseldenis** [comment]
@sebalix

**Comment by simahawk** [comment]
@rousseldenis pls rollback those statuses https://github.com/OCA/partner-contact/pull/1315 :wink:

**Pull request merged**
