### PR TITLE
lint the repo

### PR DESCRIPTION
**Pull request by lepistone**

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1: LGTM thanks!

**Comment by lepistone** [comment]
Travis confirms we're green. Yay! Most the changes are lint, while a couple were bugs (like broken imports for except_orm).

**Comment by pedrobaeza** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Remember to port it then to 8.0

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I proceed with the merge. I insist in the port to 8.0

**Comment by gurneyalex** [comment]
@pedrobaeza I did the 8.0 merge and pushed directly. 

Do we want to go through the PR process for these?

**Comment by pedrobaeza** [comment]
No, I don't think so. If you have done it, we continue now with the migration. I'm already experimenting with the new API also!!

**Comment by lepistone** [comment]
@gurneyalex @pedrobaeza I don't have strong opinion about this, but I vote for a direct push like you did. Otherwise, it would be another PR with an identical diff to one approved already.

Thanks

**Pull request merged**
