### PR TITLE
[8.0 FIX] Fix visual appereance of invoice list on stock move forms of stock_picking_invoice link

### PR DESCRIPTION
**Pull request by levkar**
Fix visual appereance of invoice list on stock move forms of stock_picking_invoice link

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@levkar Could you check why travis is red ?

**Comment by levkar** [comment]
It says: "There was an error while trying to fetch the log."
Is there a way to rerun travis?

**Comment by Cedric-Pigeon** [comment]
You have a rebuild button on the right in Travis. I made it for you.

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by levkar** [comment]
Thanks Cedric. Congrats for the PCS too :)

**Comment by pedrobaeza** [comment]
I don't consider that the current visual appearance is incorrect. It's in the context of the field "Invoiceable", which is the important thing. Can you put screenshots of before and after to check the differences?

**Comment by rousseldenis** [comment]
@levkar Can you take into account @pedrobaeza remarks and resolve conflict?

**Comment by levkar** [comment]
This has no meaning if nobody cares about it. I am closing this.

**Pull request closed without merging**
