### PR TITLE
on ship_transit, output location is not active

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by lepistone** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by guewen** [comment]
It should probably be updated to use `_location_used()` [0] as it has be done upsteam [1]

[0] https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L3027-L3034
[1] https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L3036-L3058

**Comment by gurneyalex** [comment]
part of https://github.com/OCA/stock-logistics-transport/pull/7

**Pull request closed without merging**
