### PR TITLE
[14.0][MIG] stock_picking_filter_lot

### PR DESCRIPTION
**Pull request by jesus01x**
standard migration from version 13.0 to 14.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by jesus01x** [comment]
> # Todo
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> 
> # Modules to migrate
> * [ ]  delivery_package_default_shipping_weight
> * [ ]  sale_stock_mto_as_mts_orderpoint
> * [ ]  stock_lock_lot
> * [ ]  stock_move_assign_picking_hook - By @phuctranerp - #796
> * [ ]  stock_move_line_auto_fill - By @ivantodorovich - #763
> * [ ]  stock_move_line_reference_link
> * [ ]  stock_no_negative - By @Vanneri  - #747
> * [ ]  stock_picking_auto_create_lot
> * [ ]  stock_picking_back2draft
> * [x]  stock_picking_filter_lot
> * [ ]  stock_picking_group_by_partner_by_carrier - By @phuctranerp - #795
> * [ ]  stock_picking_group_by_partner_by_carrier_by_date - By @phuctranerp - #797
> * [ ]  stock_picking_invoice_link - By @mileo - #718
> * [ ]  stock_picking_line_sequence - By @cjallais - #768
> * [ ]  stock_picking_mass_action
> * [ ]  stock_picking_purchase_order_link
> * [ ]  stock_picking_restrict_cancel_with_orig_move
> * [ ]  stock_picking_return_restricted_qty
> * [ ]  stock_picking_sale_order_link
> * [ ]  stock_picking_show_return
> * [ ]  stock_picking_whole_scrap
> * [ ]  stock_production_lot_active
> * [ ]  stock_putaway_by_route
> * [ ]  stock_putaway_hook - By @hparfr - #772
> * [ ]  stock_quant_package_dimension
> * [ ]  stock_quant_package_product_packaging
> * []  stock_return_request - By @PrapassornS - #738
> * [ ]  stock_split_picking
> 
> Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by StefanRijnhart** [comment]
Thanks for the update! Please update the version number in its separate commit, because now there is no migration commit and that's going to confuse people (or just me ;-).

**Review by alan196 — APPROVED** [review]
LGTM 👍

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update!

**Pull request merged**
