### PR TITLE
[16.0] [MIG] stock_picking_batch_extended: Migration to 16.0

### PR DESCRIPTION
**Pull request by RodrigoBM**
issue #1101

### CODE REVIEW

**Review by xAdrianCif — APPROVED** [review]
Technical review ok, thank you for the job!

**Comment by FranciscoFactorLibre** [comment]
I have reviewed, and I have seen two cases that I believe are not correct.

The first case is that when using several fields to create the batch, it only uses the first field, I attach a working video.


https://github.com/OCA/stock-logistics-workflow/assets/38328941/d0fbbd6f-106d-4c95-812b-8a18611452f4



The second case is that when using the option "Create picking batches grouped by fields" they always start in draft, without having the "draft" option checked, which I only see available in v16

Checking, in v15, the result is the same, does this result make sense? I think not, but I would like a second opinion.

**Comment by rafaelbn** [comment]
Hello @RodrigoBM , please, could you 🙏🏼 delete an create a again the README according what this module makes or improve?

Actually and reviewing the README most of the things this module says make are already made by Odoo CE

Let me know please ! Thank you! ❤️

**Comment by RodrigoBM** [comment]
> I have reviewed, and I have seen two cases that I believe are not correct.
> 
> The first case is that when using several fields to create the batch, it only uses the first field, I attach a working video.
> 
>  2023-08-14_13-21-56.mp4 
> The second case is that when using the option "Create picking batches grouped by fields" they always start in draft, without having the "draft" option checked, which I only see available in v16
> 
> Checking, in v15, the result is the same, does this result make sense? I think not, but I would like a second opinion.

- The first case is a bug that also exists in v15, this has been fixed.
- The second case is an improvement added by odoo in v16, but I didn't have it in the code migration. This is now fixed

**Comment by RodrigoBM** [comment]
> Hello @RodrigoBM , please, could you 🙏🏼 delete an create a again the README according what this module makes or improve?
> 
> Actually and reviewing the README most of the things this module says make are already made by Odoo CE
> 
> Let me know please ! Thank you! ❤️

Done

**Comment by RodrigoBM** [comment]
@oihane can you review this PR, thanks

**Review by oihane — APPROVED** [review]
LGTM

**Comment by rafaelbn** [comment]
I would like to review and write the new readme, simpler and with new screen shots

**Comment by RodrigoBM** [comment]
> I would like to review and write the new readme, simpler and with new screen shots

@rafaelbn I do it [here](https://github.com/OCA/stock-logistics-workflow/pull/1353/files#diff-62a029615c1a4df9843540fe9617f891ae917e9f86c86a1f5f7f7d86c0a98d3c)

But if you want to propose other changes, send me a PR and I'll add it.

**Comment by FranciscoFactorLibre** [comment]
I have reviewed the functionality after the last update, and I see it working correctly.

image


I have generated several delivery notes that have different destinations and contacts:

When generating the batch, I used these two fields, as grouping options,
 and created the groupings based on those criteria:

https://github.com/OCA/stock-logistics-workflow/assets/38328941/af29ee06-9eea-444f-944e-f8d3f4580c46

**Review by rafaelbn — APPROVED** [review]
Let's go! 👍🏼

**Review by FrancoMaxime — COMMENTED** [review]
@xAdrianCif @RodrigoBM With a little delay, Nice work.

**Comment by rafaelbn** [comment]
@RodrigoBM all the images in the readme are broken, do you think you can fix them? You can checkit in github or runboat, they don't work. 😢

**Comment by RodrigoBM** [comment]
> @RodrigoBM all the images in the readme are broken, do you think you can fix them? You can checkit in github or runboat, they don't work. 😢

urls fixed https://github.com/OCA/stock-logistics-workflow/pull/1399

**Pull request merged**
