### PR TITLE
[10.0][FIX]stock_cancel. quant cancellation

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Quant history last move is not always last one.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Still not working. Quant history not well kept

**Comment by AaronHForgeFlow** [comment]
This is now ready for review

**Comment by AaronHForgeFlow** [comment]
@LoisRForgeFlow  Could you remove the WIP label? In any case it seems to me there is not much people interesting on thins :cry:

**Comment by rousseldenis** [comment]
@AaronHForgeFlow What's the status of this ?

**Comment by AaronHForgeFlow** [comment]
@rousseldenis The quant history is incorrect when cancelling stock pickings using the module stock_cancel. IMHO this should be merged to fix that. Nevertheless I don't think many users use that module because of the lack of reviewers here.

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
