### PR TITLE
[15.0][MIG] stock_picking_whole_scrap: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36571

please @carlosdauden @sergio-teruel

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@CarlosRoca13 Can you review that runs with packages, please??

**Comment by CarlosRoca13** [comment]
Now, it should be working with them, thanks 4 the review

**Review by sergio-teruel — APPROVED** [review]

**Review by carlosdauden — APPROVED** [review]

**Comment by rousseldenis** [comment]
@CarlosRoca13 @carlosdauden @sergio-teruel @pedrobaeza Could you please pay attention to tests class when migrating to 15.0 ? Thanks. This will be fixed there https://github.com/OCA/stock-logistics-workflow/pull/1020

**Comment by pedrobaeza** [comment]
The deprecated warning is not something blocking, so although I agree it's advisable to change it, it's not mandatory.

**Pull request merged**
