### PR TITLE
[16.0][FW] stock_restrict_lot: Multiple ports from 14.0

### PR DESCRIPTION
**Pull request by sebalix**
Port of the following PRs from 14.0 to 16.0:
- #1179
- #1443
- #1671

The following PRs have been blacklisted:
- #1069: Already ported (commit message modified a bit, false-positive)

### CODE REVIEW

**Review by florian-dacosta — APPROVED** [review]
LGTM, thanks for the ports.
If you have time to do the same for v17 it could be nice so that the migration to 18 do not miss any commit.

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by sebalix** [comment]
@florian-dacosta yes it's planned as well, will do it ASAP

EDIT: here it is for 17.0: https://github.com/OCA/stock-logistics-workflow/pull/1715

**Review by petrus-v — APPROVED** [review]

**Comment by sebalix** [comment]
/ocabot merge minor

Minor because of the index creation

**Pull request merged**
