### PR TITLE
[17.0][IMP] stock_picking_invoice_link: Fix argument in reverse_moves

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
Next time, please check existing PRs: #1703

**Comment by JasminSForgeFlow** [comment]
> Next time, please check existing PRs: #1703

Sorry, will take care

**Pull request merged**
