### PR TITLE
[12.0][MIG] stock_picking_purchase_propagate

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration
Supersede https://github.com/OCA/stock-logistics-workflow/pull/520
cc @HaraldPanten @kos94ok-3D

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
Thanks @kittiu.
What do you think about add purchase-workflow in oca_dependencies.txt?

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by ps-tubtim — APPROVED** [review]

**Comment by kos94ok-3D** [comment]
Why not merged yet?

**Pull request merged**
