### PR TITLE
[14.0][FIX]product_supplierinfo_for_customer_picking - Wrong supplier…

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Fix for https://github.com/OCA/stock-logistics-workflow/pull/1213
@arbitora @rousseldenis @AaronHForgeFlow @MiquelRForgeFlow @tafaRU

### CODE REVIEW

**Comment by rousseldenis** [comment]
@JuanyDForgeflow Maybe a little test with the scenario explained in #1192  ?

**Review by AaronHForgeFlow — APPROVED** [review]
Code makes sense

**Comment by JuanyDForgeflow** [comment]
@rousseldenis do I squash commits or leave them like that?

**Comment by rousseldenis** [comment]
> @rousseldenis do I squash commits or leave them like that?

Your commits are clean IMHO. You can let as is. Thanks !

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
@JuanyDForgeflow Could you fordwarport this ?

**Pull request merged**
