### PR TITLE
[12.0][MIG] stock_move_quick_lot

### PR DESCRIPTION
**Pull request by kittiu**

### CODE REVIEW

**Comment by kittiu** [comment]
Done migrated

**Comment by tafaRU** [comment]
thanks @kittiu, can i remove the label `work in progress`?

**Comment by kittiu** [comment]
> thanks @kittiu, can i remove the label `work in progress`?

Yes, I think so. (I am adding more test to make green)

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by kittiu** [comment]
> Code review

@rousseldenis just curious, when you leave message "Code Review" what do you mean? :p

**Comment by rousseldenis** [comment]
> > Code review
> 
> @rousseldenis just curious, when you leave message "Code Review" what do you mean? :p

That I haven't done functional tests (on runbot)

**Comment by kittiu** [comment]
@rousseldenis do we have hard rule to greenify the codecov?
Now, it is 94% What if I can't add more test to pass it. :(

**Comment by rousseldenis** [comment]
> @rousseldenis do we have hard rule to greenify the codecov?
> Now, it is 94% What if I can't add more test to pass it. :(

Go there (codecov/patch): https://codecov.io/gh/OCA/stock-logistics-workflow/compare/a46a62e18a151718b4b854d1bb4f711c3fea4183...30992d2c16e4627ef595c4a2df928a281d350b57/diff

You need to modify tests to pass in these parts (red ones) of code.

**Review by tbaden — APPROVED** [review]
code review: lgtm

**Comment by rousseldenis** [comment]
@kittiu Do you plan to add tests or merging like this?

**Comment by kittiu** [comment]
Merge like this, ok?

**Comment by kittiu** [comment]
Fixup! Green now.

**Comment by pedrobaeza** [comment]
You can squash together all the .pot update.

**Comment by kittiu** [comment]
> You can squashed together all the .pot update.

Done

**Pull request merged**
