### PR TITLE
8.0 stock meter delay

### PR DESCRIPTION
**Pull request by chafique-delli**
add stock_meter_delay module

### CODE REVIEW

**Comment by gurneyalex** [comment]
please add an automated test.

**Comment by pedrobaeza** [comment]
Please use full and latest OCA's README template: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

Shouldn't module name should be _stock_delay_meter_ or _stock_delay_info_ instead?

**Comment by Cedric-Pigeon** [comment]
@chafique-delli  Hello, do you plan to achieve this PR ? Otherwise it will be closed in 3 days. Thanks.

**Comment by bealdav** [comment]
please close this PR. Thanks

**Pull request closed without merging**
