### PR TITLE
[16.0][MIG] stock_production_lot_active: Migration to 16.0

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Review by RodrigoBM — APPROVED** [review]
technical review, LGTM! :heart:

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by RodrigoBM** [comment]
Is it possible to rebase, to test it in runbot? @dreispt

**Comment by rousseldenis** [comment]
@dreispt Could you rebase ?

**Review by LuisNovalio — APPROVED** [review]
Testing performed in a local environment:

File:

https://github.com/user-attachments/assets/390b365b-7562-4299-9b64-4602dd78ac03

Unarchive:


https://github.com/user-attachments/assets/c12e2c24-8c5f-4698-b7fe-950db5ed8f90

Thanks.

Greetings.

**Comment by RodrigoBM** [comment]
can @rousseldenis  merge it? thanks

**Comment by RodrigoBM** [comment]
ping @rousseldenis

**Comment by RodrigoBM** [comment]
ping @OCA/logistics-maintainers

**Comment by RodrigoBM** [comment]
ping @OCA/logistics-maintainers

**Comment by rousseldenis** [comment]
/ocabot merge nobump

@RodrigoBM Don't ping so much. Contributors and maintainers will come when they have time. Thanks

**Comment by RodrigoBM** [comment]
Thank @rousseldenis  for merge this. Sorry for the pings, but we needed to translate these fields. :heart:

**Pull request merged**
