### PR TITLE
[14.0][MIG] stock_picking_send_by_mail: Migration to V14

### PR DESCRIPTION
**Pull request by ferran-S73**
Standard migration

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Odoo since v13 allows to send an automatic email for the picking when validating it, so for me this module is not needed. The only advantage of it is the possibility of sending it manually, but I wouldn't create a specific template in that case, but used the core one.

**Comment by HaraldPanten** [comment]
Well, the advantage is that user can decide which picking/s he/she wants to send by email instead of sending all of them once they're validated. Don't you think that this feature couldn't be interesting anymore?

You needed this one for V13 as well https://github.com/OCA/stock-logistics-workflow/pull/789 😝

**Comment by pedrobaeza** [comment]
It's just as I have told about the manual possibility to have it, but I'm telling about reusing the same template. FYI, we have removed the module in v13 after teaching the users about the automatic flow, and they prefer that one.

**Comment by ferran-S73** [comment]
> It's just as I have told about the manual possibility to have it, but I'm telling about reusing the same template. FYI, we have removed the module in v13 after teaching the users about the automatic flow, and they prefer that one.

@pedrobaeza I've added a commit removing the template and instead using core's template.

**Comment by pedrobaeza** [comment]
We can't merge for now due to https://github.com/OCA/maintainer-quality-tools/issues/700

**Comment by ValentinVinagre** [comment]
@pedrobaeza can it be merged ?

**Pull request merged**
