### PR TITLE
[10.0] port stock_ownership_by_move to 10.0

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
When I create a picking and I try to reserve, the status of the moves is still waiting availability, yet there are quants available for all of them:

image

**Comment by Cedric-Pigeon** [comment]
@lreficent Hello, thanks for testing. Unfortunatly I am not able to reproduce your issue. Could you provide me more details ?

**Review by carlosdauden — APPROVED** [review]
Review and tested in runbot.

@lreficent can you explain the steps to don't work?

**Review by lmignon — APPROVED** [review]
LGTM/ Code review + Functional test.

**Comment by LoisRForgeFlow** [comment]
Runbot is not working and this is already merge. I had followed the standard workflow for pickings that you all for sure followed as well. I suppose it was my mistake or some local issue, so nevermind.

**Pull request merged**
