### PR TITLE
[15.0] [MIG] `stock_production_lot_traceability`

### PR DESCRIPTION
**Pull request by ivantodorovich**
Standard migration

### CODE REVIEW

**Review by damdam-s — APPROVED** [review]

**Review by jcoux — APPROVED** [review]
Technically seems good :+1:

**Comment by ivantodorovich** [comment]
@rousseldenis this is the migration of 
- https://github.com/OCA/stock-logistics-workflow/pull/1172

Which has been merged already

**Review by rousseldenis — APPROVED** [review]
LGTM

**Pull request merged**
