### PR TITLE
[14.0][MIG] stock_picking_warn_message: Migration to 14.0

### PR DESCRIPTION
**Pull request by dhx**
Standard migration from 13.0 to 14.0

### CODE REVIEW

**Comment by rousseldenis** [comment]
@dhx Thanks for your contribution.

You can add yourself to Contributors

**Review by rousseldenis — APPROVED** [review]

**Comment by dhx** [comment]
@rousseldenis thanks for the approval, anything I can do to finish this migration? (BTW: I'll happily come back to your offer to add myself to the Contributors with the next merge request actually adding a feature to this module - just wanted to wait until this one is done first).

**Comment by dhx** [comment]
Hi @HviorForgeFlow does this migration look good to you? Works without a flaw in our odoo instances, would be great to be able to merge it :)

**Review by HviorForgeFlow — APPROVED** [review]
+1

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Comment by dhx** [comment]
Hi @rousseldenis is it possible to move this forward or do you think we need more approvals?
Happy new year :)

**Pull request merged**
