### PR TITLE
[15.0][MIG] stock_picking_show_backorder

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
This module provide a new field on stock pickings, allowing to see the
backorders associated to a picking.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@JuanyDForgeflow Thanks for this. Please change test class to TransactionCase:

image

**Comment by JuanyDForgeflow** [comment]
> @JuanyDForgeflow Thanks for this. Please change test class to TransactionCase:
> 
> image

Done!

**Review by rousseldenis — APPROVED** [review]
Code review.

Thanks for the changes on other modules

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review in runboat

**Review by sebalix — APPROVED** [review]

**Pull request merged**
