### PR TITLE
[IMP] order picking dispatchs

### PR DESCRIPTION
**Pull request by rdeheele**
It sorts the dispatch records in a descending order by date and id.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe isn't better to use planned_date?

**Comment by yvaucher** [comment]
@pedrobaeza I see no planned_date field I think the date is meant to be used as planned date?

 :+1:

**Comment by pedrobaeza** [comment]
Sorry, I got confused with stock objects.

:+1:

**Comment by rdeheele** [comment]
@yvaucher thanks!

**Pull request merged**
