### PR TITLE
[8.0] stock_ownership_availability_rules : product change quantity

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
The problem is the following :
- use link "update quantity" on product form, set a quantity
- reuse link "update quantity" on product form , set a quantity

The final quantity is the sum instead of the new quantity.

The cause is :
- the created inventory line don't contains the link to the owner,
- all quants  have an owner
- inventory line compute theorical quantity based on quants owner

depends :
- [x] https://github.com/odoo/odoo/pull/10598

### CODE REVIEW

**Comment by gurneyalex** [comment]
if your Odoo PR gets ignored, it's going to be hard to merge this one... 

Can some monkey patching be considered? I'd also welcome an OCB PR so that we can restrict the need of monkey patching to upstream only. Also may I suggest a PR against odoo master ? This has better chances of being accepted...

**Comment by sbidoul** [comment]
odoo/odoo#10598 is merged with a better hook, this PR now needs to be adapted

**Comment by Cedric-Pigeon** [comment]
@sbidoul @gurneyalex PR adapted regarding hook accepted by Odoo.

**Comment by gurneyalex** [comment]
:+1: thanks !

**Comment by rousseldenis** [comment]
:+1:

**Pull request merged**
