### PR TITLE
[13.0][MIG] stock_picking_customer_ref: Migration to 13.0

### PR DESCRIPTION
**Pull request by Olageibol**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Olageibol Thanks for this.

Next time could you follow this https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

And especially the Full process part :

image

**Review by rousseldenis — APPROVED** [review]

**Comment by Olageibol** [comment]
Hi @rousseldenis, thanks for the feedback. I've followed the same commands, as Pedro Baeza suggested in another issue, but I'll be careful in following PRs.
Regards

**Review by sebalix — APPROVED** [review]

**Pull request merged**
