### PR TITLE
[New Module] Link SO-PO when MTO or Dropship is used

### PR DESCRIPTION
**Pull request by Rad0van**
This is my lame attempt to create a module based on functionality present in _master_ branch (future 14.0) of Odoo. It links together SO and PO when MTO or Dropship is used. It shows Smart button on either SO or PO linking to associated PO or SO respectively.

@pedrobaeza suggested this is a good repository to submit if it was accepted.

Any advice, pointers and improvements are highly welcome.

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
You can find some work on that for v12 on https://github.com/OCA/purchase-workflow/pull/759, review, merge and then port to v13.
Not sure if it covers your needs.

**Comment by Rad0van** [comment]
> You can find some work on that for v12 on [OCA/purchase-workflow#759](https://github.com/OCA/purchase-workflow/pull/759), review, merge and then port to v13.
> Not sure if it covers your needs.

@HviorForgeFlow will have to have a look at that. However what I did was backporting patches in master to get that functionality. See https://github.com/odoo/odoo/pull/53933 and https://github.com/odoo/odoo/issues/52402 It works perfectly for me. Do you know why that version you are pointing wasn't merged?

**Comment by Rad0van** [comment]
So it seems all the tests pass except for 4 tests in ``stock_picking_group_by_partner_by_carrier`` Could that be that better linking of SO/PO makes it fail? Should I be concerned with it as the module is _alpha_ state?

**Comment by Rad0van** [comment]
@pedrobaeza would you care to have a look and provide some comment? Thank you.

**Comment by pedrobaeza** [comment]
Sorry, I can't follow more this question, as I have a lot of duties.

**Comment by HaraldPanten** [comment]
Hi @HviorForgeFlow @Rad0van ,

Which one should we keep/maintain? this one, or this other one (OCA/purchase-workflow#759)?

**Pull request closed without merging**
