### PR TITLE
[FIX] stock_picking_partner_note: Fix tests from unexistent variable / procurement_auto_create_group_carrier: Update function signature

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jbaudoux @JuMiSanAr

**Comment by francesco-ooops** [comment]
@GSLabIt can you take a look?

**Review by GSLabIt — APPROVED** [review]
LGTM

**Review by jbaudoux — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@jbaudoux any idea what's up? want to try again?

**Pull request merged**
