### PR TITLE
[11.0][FIX] product_expiry_simple: fix bad decorator on _action_done()

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
Here is the original _action_done() method https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move_line.py#L369
As you can see, there is no decorator on it... so we should not have @api.model on that method in this module !

**Review by HaraldPanten — APPROVED** [review]
👍  Small fix

**Review by apollet — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Fast one

**Pull request merged**
