### PR TITLE
[MIG][16.0] stock_lot_production_date

### PR DESCRIPTION
**Pull request by JuMiSanAr**
From #1162 .

### CODE REVIEW

**Comment by rousseldenis** [comment]
@JuMiSanAr Thanks for this. Could you follow migration guide especially the full process part.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

For instance, the setup folder should go into the pre-commit commit and not in migration one.

Thanks

**Comment by JuMiSanAr** [comment]
> @JuMiSanAr Thanks for this. Could you follow migration guide especially the full process part.
> 
> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch
> 
> For instance, the setup folder should go into the pre-commit commit and not in migration one.
> 
> Thanks

Hi @rousseldenis ,

Sorry for that, I had to change a few things after my first push and the pre-commit changes must have been wrongly rebased. It should be ok now.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by i-vyshnevska — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]

**Pull request merged**
