### PR TITLE
[12.0][MIG] stock_batch_ picking

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Standard migration of module stock_batch_picking to v12

cc ~ @Eficent

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I talked with @carlosdauden for using https://github.com/OCA/stock-logistics-workflow/tree/12.0/stock_picking_mass_action as base for this module, as it duplicates some code. He was about to migrate the module (or he has started already)... we should communicate before in the migration issue that someone is going to work on the migration for not duplicating efforts.

**Comment by AdriaGForgeFlow** [comment]
> I talked with @carlosdauden for using https://github.com/OCA/stock-logistics-workflow/tree/12.0/stock_picking_mass_action as base for this module, as it duplicates some code. He was about to migrate the module (or he has started already)... we should communicate before in the migration issue that someone is going to work on the migration for not duplicating efforts.

Okay, I checked the migration issue and since I didn't see anyone working on that and I had to migrate the module for a client anyway I started working on it. 
Is @carlosdauden working on it right now or expected to work on it in the near future?

Closing PR.

**Comment by pedrobaeza** [comment]
Yes, it's our fault for not communicating this, but you can keep this opened and maybe implement that idea. If no time by your part, we'll do it soon.

**Comment by sebalix** [comment]
@carlosdauden @pedrobaeza is there a branch somewhere regarding the `stock_batch_picking` module based on `stock_picking_mass_action`? We'll probably need it so if some work has been started we could contribute.

**Comment by pedrobaeza** [comment]
@sebalix not yet as this migration was low priority, so feel free to open your new one. Changes should be very straight-forward:

* Depend on that module.
* Remove a bunch of code for each method that do an action.
* Call the method on the other module.

The rest shouldn't vary.

**Comment by sebalix** [comment]
@pedrobaeza thank you, it's not a priority for us too, but for sure we'll work on it if it's not already done.

**Comment by pedrobaeza** [comment]
@sebalix module migrated in #555

**Pull request closed without merging**
