### PR TITLE
[MIG] stock_picking_auto_create_lot: Migration to 17.0

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review ok. I checked the following:
- Setting to auto create lot in the operation type and the product.
- Auto create lot in an immediate transfer.
- Auto create lot in a planned order. Also ser 2 lines in detailed operation in order to create 2 different lot.

**Comment by florenciafrigieri2** [comment]
@pedrobaeza Hi Pedro, can you please check this migration PR? Thanks in advance.

**Comment by pedrobaeza** [comment]
/ocabot migration stock_picking_auto_create_lot

@sergio-teruel do you see it correct?

**Review by sergio-teruel — APPROVED** [review]

**Pull request merged**
