### PR TITLE
[FIX] wrong uos quantity on partial deliveries

### PR DESCRIPTION
**Pull request by eLBati**
see test case

### CODE REVIEW

**Comment by yvaucher** [comment]
Some PEP8

```
./stock_picking_deliver_uos/wizard/stock_partial_picking.py:72:13: F841 local variable 'open_picking_id' is assigned to but never used
./stock_picking_deliver_uos/wizard/stock_partial_picking.py:78:80: E501 line too long (81 > 79 characters)
./stock_picking_deliver_uos/wizard/stock_partial_picking.py:82:80: E501 line too long (83 > 79 characters)
./stock_picking_deliver_uos/wizard/stock_partial_picking.py:90:80: E501 line too long (80 > 79 characters)
```

**Comment by eLBati** [comment]
Thanks @yvaucher , fixed

**Comment by yvaucher** [comment]
@eLBati For PEP8 issues, you can do `git commit --amend` as IMO commit to fix pep8 are a bit noisy.

Plus there is still an issue there:

```
2015-01-29 17:08:09,458 23715 INFO openerp_test openerp.modules.loading: module stock_picking_deliver_uos: loading test/stock_partial_picking.yml
2015-01-29 17:08:09,479 23715 TEST openerp_test openerp.tools.yaml_import: I create a picking OUT
2015-01-29 17:08:09,584 23715 TEST openerp_test openerp.tools.yaml_import: I add lines
2015-01-29 17:08:09,636 23715 TEST openerp_test openerp.tools.yaml_import: Then I confirm the picking
2015-01-29 17:08:09,782 23715 TEST openerp_test openerp.tools.yaml_import: Then I force the Assignment
2015-01-29 17:08:09,836 23715 TEST openerp_test openerp.tools.yaml_import: I create a stock.partial picking, check default values, Onchange method and i deliver the picking
2015-01-29 17:08:10,344 23715 TEST openerp_test openerp.tools.yaml_import: Finally i check picking line after deliver
2015-01-29 17:08:10,348 23715 ERROR openerp_test openerp.tools.yaml_import: AssertionError in Python code : Wrong product_uos_qty on line on product_24: 2.0
```

**Comment by eLBati** [comment]
Hello @yvaucher the error depends on a bug I found in `check_assign` method: https://github.com/odoo/odoo/pull/4829

**Comment by pedrobaeza** [comment]
As Travis is red and no fix, I close. Feel free to reopen in case there's interest.

**Pull request closed without merging**
