### PR TITLE
[FIX] stock_no_negative: Use should_bypass_reservation

### PR DESCRIPTION
**Pull request by etobella**
It was giving errors when using scrap locations.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@etobella Could you add a test case for this ?

**Comment by etobella** [comment]
I will create the test, but it is an standard feature of odoo:
https://github.com/odoo/odoo/blob/11.0/addons/stock/models/stock_move_line.py#L223

**Comment by rousseldenis** [comment]
Ok. But I didn't speak about testing the function itself. But adding a test case to highlight that the no negative flow works with scrap locations now

**Comment by rousseldenis** [comment]
@etobella I think by the way this is weird to install that module and authorize negative quants on scrap locations. In which case do you need this ?

**Comment by etobella** [comment]
In my case, I have some locations where stock could be negative for products.
currently, this module is disallowing to have negative stock on all locations internal locations.
Maybe, the right solution should be creating a new flag for allow_negative on locations

**Pull request closed without merging**
