### PR TITLE
[10.0] Add support for lots in stock_pack_operation_auto_fill

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@alexis-via Travis seems weird. Could you maybe rebase ?

**Comment by alexis-via** [comment]
Rebased, let's see what Travis says now...

**Comment by pedrobaeza** [comment]
Isn't this the same as https://github.com/OCA/stock-logistics-workflow/tree/10.0/stock_picking_transfer_lot_autoassign?

**Comment by alexis-via** [comment]
@pedrobaeza According to the description, it seems it's the same. So I fear we have in the OCA 2 modules that do almost the same thing... which is very bad!

**Comment by pedrobaeza** [comment]
Well, if it serves, we merge both in v11 under this one. For v10, you can just use the existing one, and switch to the new one in v11.

**Comment by pedrobaeza** [comment]
Extra info: this PR was the one where we did that: #435

**Comment by rousseldenis** [comment]
@alexis-via Does the proposition from @pedrobaeza fits your needs ?

**Comment by rousseldenis** [comment]
@alexis-via

**Comment by rousseldenis** [comment]
@alexis-via

**Comment by rousseldenis** [comment]
@alexis-via We will close this soon as no answer

**Pull request closed without merging**
