### PR TITLE
[15.0][MIG] stock_picking_product_assortment_availavility_inline: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT40157

ping @CarlosRoca13 @carlosdauden

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Comment by rousseldenis** [comment]
/ocabot migration stock_picking_product_assortment_availavility_inline

**Review by carlosdauden — APPROVED** [review]
I approve even with misspelling in name :wink:

**Comment by pedrobaeza** [comment]
Hehe, maybe we should rename it then?

**Comment by pedrobaeza** [comment]
ping @sergio-teruel do we rename it?

**Comment by sergio-teruel** [comment]
Yes... of course....
What is the procedure?

**Comment by pedrobaeza** [comment]
```
git filter-branch --tree-filter 'if [ -d old_module_name ]; then mv old_module_name new_module_name; fi' HEAD
```

and change the POT file and PO/POT content, and maybe any absolute XML-ID reference in the code.

**Comment by rousseldenis** [comment]
@sergio-teruel

**Comment by sergio-teruel** [comment]
Do you know why this PR was closed automatically??

**Comment by pedrobaeza** [comment]
You force pushed in the source branch something with unrelated commit history to the target branch. I think you forgot to do the rebase after the renaming.

**Pull request closed without merging**
