### PR TITLE
[16.0][MIG] stock_picking_batch_extended: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT43380

This PR superseeds #1236 

@pedrobaeza please review!

### CODE REVIEW

**Comment by rousseldenis** [comment]
@stefan-tecnativa Why supsersedes as  @BorisFL has attended all remarks two weeks ago. Could you review that one instead ?

**Comment by stefan-tecnativa** [comment]
> @stefan-tecnativa Why supsersedes as @BorisFL has attended all remarks two weeks ago. Could you review that one instead ?

I need the migration of this module to be completed and since there had been no activity for two weeks, I decided to take the initiative and do it myself. However, I will review the PR as well

**Comment by rousseldenis** [comment]
> > @stefan-tecnativa Why supsersedes as @BorisFL has attended all remarks two weeks ago. Could you review that one instead ?
> 
> I need the migration of this module to be completed and since there had been no activity for two weeks, I decided to take the initiative and do it myself. However, I will review the PR as well

A gentle ping to the author is always welcome :smiley:

**Comment by xAdrianCif** [comment]
Hi! A colleague has carried out the migration that was postponed in this issue. I'll leave the link here in case you're still interested. Thank you!

https://github.com/OCA/stock-logistics-workflow/pull/1353

**Pull request closed without merging**
