### PR TITLE
[10.0] [MIG] stock_disable_force_availability_button

### PR DESCRIPTION
**Pull request by fanha99**
first times to make pull request.
Just clone the v9, change some value, tested on local.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please sign the CLA and follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by sebalix** [comment]
Hi @fanha99 , thank you for this PR.
However the Git history is not preserved, you must follow the migration guide available here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by Cedric-Pigeon** [comment]
Hi @fanha99 Do you still plan to work on this PR ?

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @fanha99 I'm working on migration of this module. As it is not on a separate branch on @fanha99 repo, I propose to create a new PR and close this. I cherry-picked this commit

**Pull request closed without merging**
