### PR TITLE
[16.0] [MIG] stock_picking_batch_extended_account_sale_type

### PR DESCRIPTION
**Pull request by Shide**
Straight forward migration, nothing changed.

Dependant PR: https://github.com/OCA/stock-logistics-workflow/pull/1395

MT-3612 @moduon @rafaelbn @ernestotejeda @sergio-teruel @fcvalgar @yajo please review if you want :)

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Code review.

**Comment by Shide** [comment]
**note:** rebased to obtain `stock_picking_batch_extended_account` dependency

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM thank you @Shide 

image

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
