### PR TITLE
[17.0][MIG] stock_restrict_lot: Migration to 17.0

### PR DESCRIPTION
**Pull request by yannoliv**

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
Functional review 👍  LGTM

**Review by sanderlienaerts — APPROVED** [review]
LGTM

**Comment by sanderlienaerts** [comment]
May be closed, `stock_restrict_lot` was merged in https://github.com/OCA/stock-logistics-workflow/pull/1652

**Comment by sebalix** [comment]
Closing, module merged in 17.0 there: https://github.com/OCA/stock-logistics-workflow/pull/1652
Thank you :pray:

**Pull request closed without merging**
