### PR TITLE
[IMP] stock_lock_lot, mrp_lock_lot: allow to move locked lot in specific locations

### PR DESCRIPTION
**Pull request by agaldona**
This is for internal movements, purchases or inventory, using the configuration to allow move locked lots in some cases and not in other.

### CODE REVIEW

**Review by oihane — APPROVED** [review]
LGTM :+1:

**Comment by oihane** [comment]
Travis failing is unrelated to this PR.

**Comment by Daniel-CA** [comment]
:+1:

**Comment by agaldona** [comment]
can anyone check this out, please?
cc @sbidoul @hbrunn @gurneyalex @clonedagain @pedrobaeza

**Review by Cedric-Pigeon — APPROVED** [review]

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza I think this one can be merged

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please change version number

**Comment by agaldona** [comment]
Version number already changed

**Pull request merged**
