### PR TITLE
[16.0] [MIG] stock_lock_lot: Migration to 16.0

### PR DESCRIPTION
**Pull request by AdrianaSaiz**
Standard migration

### CODE REVIEW

**Review by alejandro-vallejoFL — APPROVED** [review]
LGTM, good job!

**Review by Alber1998 — APPROVED** [review]
Good job! 
Funcional review completed!
LGTM

**Comment by AdrianaSaiz** [comment]
Hi, could someone from @OCA/logistics-maintainers check this PR?

**Review by hparfr — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
