### PR TITLE
[12.0][ADD] New module stock_landed_costs_currency

### PR DESCRIPTION
**Pull request by novawish**

### CODE REVIEW

**Review by tbaden — CHANGES_REQUESTED** [review]
please fix the runbot warning:
openerp_test odoo.addons.base.models.ir_model: Two fields (currency_price_unit, price_unit) of stock.landed.cost.lines() have the same label: Cost.

please use the maintainer tools to create a readme
https://github.com/OCA/maintainer-tools

code review: lgtm

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@novawish Do you plan to add tests to increase coverage ?

**Review by tbaden — APPROVED** [review]
runbot is green now

**Comment by rousseldenis** [comment]
@novawish Any news on this ?

**Comment by novawish** [comment]
@rousseldenis I added some tests but i don't know why the runbot and travis did not run again.

**Comment by rousseldenis** [comment]
@novawish It's green. Is this ok for you ?

**Comment by novawish** [comment]
@rousseldenis  Yeah ok for me. I added some tests already but apparently it's not enough to cover the code (is it strange?). The codecovs are still in red

**Comment by rousseldenis** [comment]
> @rousseldenis Yeah ok for me. I added some tests already but apparently it's not enough to cover the code (is it strange?). The codecovs are still in red

If you want to know which lines are not tested, click on 'Details' link next to coverage/patch and go to 'Diff' tab in Coverage.io. Lines in red are not tested.

Do you want to add test for that (in your case: the onchange method and the case cost currency is different of company currency) ?

**Comment by novawish** [comment]
@rousseldenis All passed now, thanks for helping me, i did not know that before

**Pull request merged**
