### PR TITLE
[MIG][13.0] stock_picking_mass_action: Migration to v13.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT21726
@carlosdauden @Tardo review

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
Functional and code review: OK

**Review by Tardo — APPROVED** [review]
:+1: LGTM

**Review by carlosdauden — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
