### PR TITLE
[14.0][MIG] stock_picking_auto_create_lot

### PR DESCRIPTION
**Pull request by ValentinVinagre**

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten all green

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Comment by ValentinVinagre** [comment]
@manuelregidor can u review please?

**Review by Saran440 — APPROVED** [review]
LGTM, No major change :+1:

**Comment by HaraldPanten** [comment]
@JordiBForgeFlow @LoisRForgeFlow

**Comment by HaraldPanten** [comment]
> /ocabot merge patch

THX!!

**Comment by rousseldenis** [comment]
@ValentinVinagre Could you rebase ?

**Comment by ValentinVinagre** [comment]
> @ValentinVinagre Could you rebase ?

Done

**Pull request merged**
