### PR TITLE
[15.0][ADD] stock_picking_batch_outgoing: New module to get outgoing batch picking in origin chained pickicngs

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT47997

ping @pilarvargas-tecnativa @CarlosRoca13 

This module depends on:

- [x] https://github.com/OCA/stock-logistics-workflow/pull/1522

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Comment by rousseldenis** [comment]
@sergio-teruel FYI, there is something that could be in your interest : https://github.com/OCA/stock-logistics-workflow/tree/16.0/stock_move_propagate_first_move

**Comment by sergio-teruel** [comment]
Thanks @rousseldenis I will do teh backport to use it as base module..

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
