### PR TITLE
[14.0][MIG] - stock_picking_mass_action

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sbejaoui Maybe this should be checked functionally as some actions are standard:

image

**Comment by rousseldenis** [comment]
And travis is red

**Comment by sbejaoui** [comment]
> @sbejaoui Maybe this should be checked functionally as some actions are standard:
> 
> image

This module allows to validate a picking in any state by going through all the stages. IMO, it's different from the standard validate action and quite useful

**Comment by hailangvn** [comment]
Good day @sbejaoui, please kindly update status of this PR.

**Comment by hailangvn** [comment]
@sbejaoui, please kindly advise if you will continue this or not.

**Comment by rousseldenis** [comment]
Closing this as no answer. Supersedes by #973

**Pull request closed without merging**
