### PR TITLE
[14.0] [MIG] sale_line_returned_qty

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@JasminSForgeFlow Oops, seems module version is in pre-commit commit. Can you change ?

**Comment by JasminSForgeFlow** [comment]
> @JasminSForgeFlow Oops, seems module version is in pre-commit commit. Can you change ?

Updated, Thanks

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by tafaRU — APPROVED** [review]

**Pull request merged**
