### PR TITLE
[8.0][ADD]:Module stock_picking_send_by_mail

### PR DESCRIPTION
**Pull request by percevaq**
Backport from 9.0 to 8.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history.

**Comment by percevaq** [comment]
> Please preserve commit history.
Pedro, do you give me more details about this?

**Comment by rousseldenis** [comment]
@percevaq See discussion here https://github.com/OCA/stock-logistics-workflow/pull/187#issuecomment-456349429

**Comment by quentinDupont** [comment]
I open an other PR with commit history : https://github.com/OCA/stock-logistics-workflow/pull/492
Hope this is good

**Pull request closed without merging**
