### PR TITLE
[17.0][MIG] stock_restrict_lot

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by jcadhoc** [comment]
I don`t understand why test is failing, it says that argument location_id isn´t in function and it is, i compared with another places it shows and it`s the same way

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@jcadhoc Could you fix tests ? Thanks

**Comment by StefanRijnhart** [comment]
@jcadhoc 

```
 2024-07-10 14:53:10,538 248 ERROR odoo odoo.addons.stock_restrict_lot.tests.test_restrict_lot: ERROR: TestRestrictLot.test_procurement_with_2_steps_output
Traceback (most recent call last):
  File "/__w/stock-logistics-workflow/stock-logistics-workflow/stock_restrict_lot/tests/test_restrict_lot.py", line 215, in test_procurement_with_2_steps_output
    assert_move_line_per_lot_and_location(
  File "/__w/stock-logistics-workflow/stock-logistics-workflow/stock_restrict_lot/tests/test_restrict_lot.py", line 194, in assert_move_line_per_lot_and_location
    self.assertEqual(concern_move_line.reserved_uom_qty, expect_reserved_qty)
AttributeError: 'stock.move.line' object has no attribute 'reserved_uom_qty'
```

**Comment by StefanRijnhart** [comment]
BTW there already was https://github.com/OCA/stock-logistics-workflow/pull/1550 but its CI does not look any better.

**Comment by StefanRijnhart** [comment]
And I would be curious to know what you think about https://github.com/OCA/stock-logistics-workflow/pull/1560.

**Comment by peluko00** [comment]
Any update @jcadhoc?

**Comment by jcadhoc** [comment]
@rousseldenis Thanks for reminder, i will see it

**Comment by jcadhoc** [comment]
@StefanRijnhart Sorry, i didnt see the older pr, for me its the same if i give +1 or we merge this, technically seems the same but my pr have precommit ok.

**Review by sanderlienaerts — APPROVED** [review]
Migration seems OK.

**Comment by StefanRijnhart** [comment]
@jcadhoc No, go ahead, the other PR is not responding. Can you check my other comments?

**Comment by jcadhoc** [comment]
@rousseldenis @StefanRijnhart All green this time!

Sorry for the delay, i think it's ok to merge, let mi know if i miss something else..

Thank you!

**Comment by StefanRijnhart** [comment]
Thanks, looking good now. Please squash the last commit `[IMP] : pre-commit auto fixes` into the migration commit as it corrects the linting of a change in that commit.

**Comment by jcadhoc** [comment]
@StefanRijnhart Ready!

Thanks for guide me :)

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by peluko00** [comment]
It's ready for merge @StefanRijnhart?

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Comment by StefanRijnhart** [comment]
@peluko00 Yes!

/ocabot merge nobump

**Pull request merged**
