### PR TITLE
[MIG] stock_production_lot_active: Migration to 15.0 

### PR DESCRIPTION
**Pull request by BT-dmontull**

### CODE REVIEW

**Comment by BT-dmontull** [comment]
@StefanRijnhart could you merge this? I saw you merged the migration to 14.0: https://github.com/OCA/product-attribute/pull/820

**Comment by rousseldenis** [comment]
> @StefanRijnhart could you merge this? I saw you merged the migration to 14.0: [OCA/product-attribute#820](https://github.com/OCA/product-attribute/pull/820)

@BT-dmontull OCA rules for merge is to have at least 5 days and two approvals. Usually, it's fair to review other PR's too.

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by StefanRijnhart** [comment]
The tree view of this module is called `stock_production_lot_search_view` and the other way around. Can you fix that?

**Comment by BT-dmontull** [comment]
@StefanRijnhart I fixed It, but now doesn't pass runbot test. And It's because yesterday rsync change version in ubuntu repositories (from rsync_3.1.3-8ubuntu0.1_amd64.deb to rsync_3.1.3-8ubuntu0.2_amd64.deb)
what should i do to fix it?
Thanks

**Comment by rousseldenis** [comment]
> @StefanRijnhart I fixed It, but now doesn't pass runbot test. And It's because yesterday rsync change version in ubuntu repositories (from rsync_3.1.3-8ubuntu0.1_amd64.deb to rsync_3.1.3-8ubuntu0.2_amd64.deb) what should i do to fix it? Thanks

I've created an issue here : https://github.com/sbidoul/runboat/issues/48

We need to wait.

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update! The runboat error should not be blocking.

**Comment by rousseldenis** [comment]
> Thanks for the update! The runboat error should not be blocking.

We can launch the merge for sure.

**Pull request merged**
