### PR TITLE
[13.0][MIG] stock_landed_costs_currency

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard migration.

### CODE REVIEW

**Comment by newtratip** [comment]
@ps-tubtim Can you solve the conflict file ?

**Comment by ps-tubtim** [comment]
@newtratip Thank you, I resolved this conflict.

**Comment by newtratip** [comment]
Hello @ps-tubtim Can you check your travis-ci ?

**Comment by ps-tubtim** [comment]
@newtratip I resolved all.

**Comment by JrDevCX001** [comment]
@ps-tubtim ,

I have just tested this on 13.0 in a local env and have found the following issues:

- stock.landed.cost.currency_id seems to be readonly in the form view in all states
- when adjusting the form view to readonly="0" for stock.landed.cost.currency_id and then trying to manually switch the currency from the default base company currency to another currency (in my case HKD) the field switches back to the base company currency when clicking save.

I have attempted to rebuild the runbot for this PR on runbot (OCA), however the build is in the pending state and therefore i'm not able to test on runbot to confirm.

## UPDATE:
I've just tested this in the runbot, and the same behaviour is present as mentioned above. stock.landed.cost.currency_id and stock.landed.cost.lines.currency_id both revert back to the base company currency when the save button is clicked. I have made the currency_id on lines visible and made the currency_id readonly="0" to demonstrate what is going on.

## DEMONSTRATION IN OCA RUNBOT:
New - Odoo

**Comment by ps-tubtim** [comment]
@JrDevCX001 Thank you for your review. I fixed this.

Peek 2020-08-06 11-22

**Comment by rousseldenis** [comment]
@ps-tubtim Can you fix pre-commit issue? 

Tip: to avoid this, install pre-commit locally before committing, it will reformat for you.

**Comment by ps-tubtim** [comment]
@rousseldenis I fixed pre-commit issue.

**Review by mamcode — APPROVED** [review]
LGTM, Thanks!

**Comment by andres-pcg** [comment]
@ps-tubtim Travis is crying here. Can you please check it out?

**Comment by gustavovalverde** [comment]
@rousseldenis this build errored, could you rebuild it?

**Comment by rousseldenis** [comment]
@gustavovalverde done. Still problems with pre-commit. @ps-tubtim

**Comment by andres-pcg** [comment]
This is green @rousseldenis 🙌

**Review by rousseldenis — APPROVED** [review]

**Comment by andres-pcg** [comment]
@pedrobaeza can you merge this?

**Comment by pedrobaeza** [comment]
Well, you have to rebase to check the problem in previous merge.

**Comment by andrp92** [comment]
Which problem? I see all green and @rousseldenis Approve it. Can you tell us exactly what to do? It's being a while since this was migrated. Please assist us. Thanks. 

> this commit of 13.0-ocabot-merge-pr-614-by-rousseldenis-bump-patch

@ps-tubtim can you please check this out? Thanks a lot for your contribution!

**Comment by andres-pcg** [comment]
> @rousseldenis your merge command was aborted due to failed check(s), which you can inspect on [this commit of 13.0-ocabot-merge-pr-614-by-rousseldenis-bump-patch](https://github.com/OCA/stock-logistics-workflow/commits/7254a0b8c0dad8e9f7216bdbc5fb2ed676b2bd29).
> 
> After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

@ps-tubtim can you please check this out? Thanks a lot for your contribution!

**Comment by andres-pcg** [comment]
@pedrobaeza thanks for the heads up. I just mentioned @ps-tubtim so she can check it out.

**Review by newtratip — APPROVED** [review]

**Comment by andres-pcg** [comment]
Hey @ps-tubtim , 

Seems like Oca-bot is yelling here:

https://github.com/OCA/stock-logistics-workflow/commits/7254a0b8c0dad8e9f7216bdbc5fb2ed676b2bd29

**Pull request merged**
