### PR TITLE
[14.0][MIG] stock_landed_costs_delivery: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Changes done:
- [x] `stock_landed_costs_purchase_auto`: Improve tests + Backorder compatibility
- [x] `stock_landed_costs_purchase_auto`: Allow create `stock.landed.cost` without advanced permissions
- [x] `stock_landed_costs_delivery`: Migration to 14.0
- [x] `stock_landed_costs_delivery`:  Auto-validate Landed Costs when linked purchase pickings are done

Locked by:
- [x] `delivery_purchase`: https://github.com/OCA/delivery-carrier/pull/725

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT45656

### CODE REVIEW

**Comment by victoralmau** [comment]
Ping @pedrobaeza and @chienandalu

**Review by pedrobaeza — APPROVED** [review]

**Review by carolinafernandez-tecnativa — APPROVED** [review]
TT45656

**Pull request merged**
