### PR TITLE
stock_route_transit: fix picking type location update

### LINKED ISSUE #62: stock_route_transit: transit picking type src and dest locations not updated

### PR DESCRIPTION
**Pull request by gurneyalex**
closes #62

### CODE REVIEW

**Comment by gurneyalex** [comment]
build should get green once https://github.com/odoo/odoo/pull/5193 is merged.

**Comment by lepistone** [comment]
yup :+1:

**Comment by guewen** [comment]
:+1:

**Comment by lepistone** [comment]
The fix is merged upstream and in OCB. I restarted the red job.

**Comment by lepistone** [comment]
@gurneyalex red because of a long line.

**Pull request merged**
