### PR TITLE
Add workflow trigger on picking after assigning move

### PR DESCRIPTION
**Pull request by mdietrichc2c**
This PR is to add a needed `wkf_trigger` on picking after the mass assign on stock moves; it was called before in https://github.com/OCA/OCB/blob/7.0/addons/stock/stock.py#L2229 , but that is not the case anymore.

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1: an automated test would be nice and would have caught the bug.

**Comment by guewen** [comment]
:+1:

**Comment by gurneyalex** [comment]
@mdietrichc2c  could you rebase your PR on top of https://github.com/OCA/stock-logistics-workflow/pull/164 and modify the tests I added there so that they fail without your patch?

**Comment by mdietrichc2c** [comment]
@gurneyalex done: I add a check on the picking (assigned after all the moves are assigned). It fails without the fix, and works with it.

**Comment by lepistone** [comment]
:+1: thanks!

**Pull request merged**
