### PR TITLE
separate the picking_dispatch tests

### PR DESCRIPTION
**Pull request by gurneyalex**
picking dispatch adds a dependency on delivery
and the presence of this module breaks the tests of stock_ownership_by_move
(but the module works fine with delivery installed)

### CODE REVIEW

**Comment by yvaucher** [comment]
What about using global values as in https://github.com/OCA/maintainer-quality-tools/blob/master/.travis.yml

```
 env:
  global:
    - VERSION="8.0" TESTS="0" LINT_CHECK="0"
  matrix:
    - LINT_CHECK="1"
    - TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="picking_dispatch"
    - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="picking_dispatch"
    - TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="picking_dispatch"
    - TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="picking_dispatch"
```

**Comment by lepistone** [comment]
Maybe it's not necessary to split. Let me check.

**Comment by lepistone** [comment]
I found the actual reason of the red test (a bug in the odoo test launcher). I'll file an issue, and report back here.

**Comment by yvaucher** [comment]
@lepistone Anything new about your last comment?

Tests are red again thought we splitted tests

**Comment by yvaucher** [comment]
Tests fails due to https://github.com/odoo/odoo/pull/6824

The official fix make impossible to confirm a purchase order with both purchase and sale invoice generation policies based on picking

**Comment by lepistone** [comment]
@yvaucher and I added two fixes that should make things green on odoo. Hopefully on OCB tomorrow.

**Comment by yvaucher** [comment]
Should be green for Odoo but red for OCB as https://github.com/odoo/odoo/pull/6931 was just merged :+1:

**Comment by yvaucher** [comment]
restarting Job #466.2 it was only timed out

**Comment by yvaucher** [comment]
And it's green

**Comment by florian-dacosta** [comment]
:+1: 
Thanks a lot for your work on this!

**Comment by yvaucher** [comment]
Ok I merge it and restart build of other PRs

**Comment by tafaRU** [comment]
> Thanks a lot for your work on this!

+1

**Pull request merged**
