### PR TITLE
[IMP] stock_quant_package_dimension: Don't rely on max_weight on product.packaging + change weight_uom_name type

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

- https://github.com/OCA/product-attribute/pull/1386

### CODE REVIEW

**Comment by rousseldenis** [comment]
@jbaudoux

**Review by jbaudoux — APPROVED** [review]

**Comment by rousseldenis** [comment]
@jbaudoux @lmignon I've added a change here to remove warnings about default on related field (changed to original computed one).

**Review by lmignon — APPROVED** [review]

**Review by bosd — APPROVED** [review]

**Comment by bosd** [comment]
Let's hope we can merge this soon. As CI tests are broken.

**Pull request merged**
