### PR TITLE
[11.0][MIG] stock picking show return

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot..." commits and check Travis

**Comment by pedrobaeza** [comment]
Travis is still red. And please squash migration commits together.

**Comment by fmdl** [comment]
@pedrobaeza it is done. Thanks

**Comment by pedrobaeza** [comment]
There are conflicts right now, so I can't merge. Can you rebase?

**Comment by fmdl** [comment]
@pedrobaeza it is done. Thanks

**Review by pedrobaeza — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
