### PR TITLE
[16.0][FIX] stock_picking_batch_extended: correction of the url of the read…

### PR DESCRIPTION
**Pull request by RodrigoBM**
…me images

### CODE REVIEW

**Comment by RodrigoBM** [comment]
fix for you coment @rafaelbn  https://github.com/OCA/stock-logistics-workflow/pull/1353#issuecomment-1764219672

**Review by xAdrianCif — APPROVED** [review]
well done @RodrigoBM thanks so much!

**Comment by RodrigoBM** [comment]
ping @rafaelbn

**Comment by rafaelbn** [comment]
Thanks @RodrigoBM , we are going to propose you here an little improvement in the readme, we are going to write you down in order you can copy-paste if possible. OK? 🙏🏼 😄 

@moduon MT-3972

**Review by carlosdauden — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The way to do this correctly is through relative paths with `..` in it. Please check examples in https://raw.githubusercontent.com/OCA/web/16.0/web_responsive/readme/DESCRIPTION.rst

**Comment by RodrigoBM** [comment]
> The way to do this correctly is through relative paths with `..` in it. Please check examples in https://raw.githubusercontent.com/OCA/web/16.0/web_responsive/readme/DESCRIPTION.rst

I'll change it, even if I look at this example. https://raw.githubusercontent.com/OCA/account-financial-tools/16.0/account_fiscal_position_vat_check/readme/USAGE.rst

**Comment by pedrobaeza** [comment]
That one should be changed also.

**Comment by RodrigoBM** [comment]
> Thanks @RodrigoBM , we are going to propose you here an little improvement in the readme, we are going to write you down in order you can copy-paste if possible. OK? 🙏🏼 😄
> 
> @moduon MT-3972

I await your proposal for change.

**Comment by Gelojr** [comment]
Hi @RodrigoBM 😄
Thank you for the readme. We went through it and had a few questions. As @rafaelbn said, we have prepared a more detailed readme so you can copy and paste if possible. It has other images that explain in more detail what is included in the module.
Thanks and regards.




## stock_picking_batch_extended
This module:

- Adds extra fields to the batch picking creation wizard
- Adds extra fields and functionalities to the batch picking form.

### Configuration
In Inventory / Settings it is possible to activate or deactivate which approach for batch handling will be used per company. By default after installation this option will be activated for all companies.
image

### Usage
When you create a batch pick, the creation wizard will appear with the new fields added.
image

1. Name: Allows to rename the batch. But be careful, if this is done, it overwrites the name that Odoo assigns to the batch by default.
2. Notes: Allows to add notes to the batch.
3. Allows you to group the batch by the fields of the model stock_picking

Adds to the form view of batch picking:
#### In "Draft" status:
image

1. Delete all delivery notes in the batch whose status is not done or canceled.
2. Print pickings.
3. Smart button with counting and access to pickings.
4. Rename the batch if it is in draft status.
5. Date. On which the batch picking is to be processed.
6. Notes. Reflects the notes that have been entered from the wizard and allows you to modify them.
7. Delete all delivery notes from the batch whose status is not done or canceled.
8. Allows to add more fields to the list of pickings.

#### "In progress" status
image

1. Delete all pickings in the batch whose status is not done or cancelled.
2. Print pickings.
3. Smart button with counting and access to pickings.
4. Date. On which the batch picking is to be processed. It can be changed in this state.
5. Notes. Reflects the notes that have been entered from the wizard and allows you to modify them.
6. Allows to add more fields to the list of pickings.

Note: If a batch is cancelled, it cancels all batch picks and sets the batch statuses to cancel as well only if the user has set the OCA batch validation approach in the inventory settings.

#### Status "Done"
image

1. Print pickings.
2. Smart button with counting and access to pickings.
3. Date. On which the batch picking is to be processed. Already it can’t be modified in this state.
4. Notes. Reflects the notes that have been entered from the wizard and allows you to modify them.


@moduon  MT-3972

**Comment by RodrigoBM** [comment]
> Hi @RodrigoBM 😄 Thank you for the readme. We went through it and had a few questions. As @rafaelbn said, we have prepared a more detailed readme so you can copy and paste if possible. It has other images that explain in more detail what is included in the module. Thanks and regards.
> 
> ## stock_picking_batch_extended
> This module:
> 
> * Adds extra fields to the batch picking creation wizard
> * Adds extra fields and functionalities to the batch picking form.
> 
> ### Configuration
> In Inventory / Settings it is possible to activate or deactivate which approach for batch handling will be used per company. By default after installation this option will be activated for all companies. image
> 
> ### Usage
> When you create a batch pick, the creation wizard will appear with the new fields added. image
> 
> 1. Name: Allows to rename the batch. But be careful, if this is done, it overwrites the name that Odoo assigns to the batch by default.
> 2. Notes: Allows to add notes to the batch.
> 3. Allows you to group the batch by the fields of the model stock_picking
> 
> Adds to the form view of batch picking:
> 
> #### In "Draft" status:
> image
> 
> 1. Delete all delivery notes in the batch whose status is not done or canceled.
> 2. Print pickings.
> 3. Smart button with counting and access to pickings.
> 4. Rename the batch if it is in draft status.
> 5. Date. On which the batch picking is to be processed.
> 6. Notes. Reflects the notes that have been entered from the wizard and allows you to modify them.
> 7. Delete all delivery notes from the batch whose status is not done or canceled.
> 8. Allows to add more fields to the list of pickings.
> 
> #### "In progress" status
> image
> 
> 1. Delete all pickings in the batch whose status is not done or cancelled.
> 2. Print pickings.
> 3. Smart button with counting and access to pickings.
> 4. Date. On which the batch picking is to be processed. It can be changed in this state.
> 5. Notes. Reflects the notes that have been entered from the wizard and allows you to modify them.
> 6. Allows to add more fields to the list of pickings.
> 
> Note: If a batch is cancelled, it cancels all batch picks and sets the batch statuses to cancel as well only if the user has set the OCA batch validation approach in the inventory settings.
> 
> #### Status "Done"
> image
> 
> 1. Print pickings.
> 2. Smart button with counting and access to pickings.
> 3. Date. On which the batch picking is to be processed. Already it can’t be modified in this state.
> 4. Notes. Reflects the notes that have been entered from the wizard and allows you to modify them.
> 
> @moduon MT-3972

Done. As the images are new I understand that they are not yet in github and for that reason they are not seen but when the merge is done, everything will be seen correctly.

Selección_566

Can you check it!

Thanks

**Comment by RodrigoBM** [comment]
ping @Gelojr @rafaelbn

**Review by Gelojr — APPROVED** [review]
If, as @RodrigoBM says, the images will look good when the merge is done, I see it as OK.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by RodrigoBM** [comment]
I have checked that the images can be seen in runboat.

Selección_567

Thanks @Gelojr @pedrobaeza  @rafaelbn

**Comment by Gelojr** [comment]
@RodrigoBM 
Due to the PR  #1404   it would be necessary to change this image
276277412-cab9d9e0-623e-4673-8472-7ca3c1680b87
for this one.
2023-10-23 17_53_55-Odoo - Settings
Thanks

**Comment by RodrigoBM** [comment]
> @RodrigoBM Due to the PR #1404 it would be necessary to change this image 276277412-cab9d9e0-623e-4673-8472-7ca3c1680b87 for this one. 2023-10-23 17_53_55-Odoo - Settings Thanks


@Gelojr  If the view is changed in that PR, it will be in that PR that the image in the readme will change.

**Pull request merged**
