### PR TITLE
[12.0][IMP] stock_return_request: Get sub locations. Get quant location for quants if possible

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa
ping @chienandalu

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1: Regression testing should be as easy as making a sub-location of the main one and receiving the stock on it: https://github.com/OCA/stock-logistics-workflow/blob/aae5730a4397006fbf790a8064aa3a2ac125218f/stock_return_request/tests/test_stock_return_request_common.py#L62

**Comment by pedrobaeza** [comment]
Yes, please include tests for these extended behavior

**Comment by sergio-teruel** [comment]
@pedrobaeza @chienandalu Test done...

**Review by chienandalu — APPROVED** [review]
Great :+1:

**Comment by pedrobaeza** [comment]
@sergio-teruel instead of putting `[WIP]` in the title (that you forget to remove), you can use draft PR state, that you can control in any moment.

/ocabot merge patch

**Pull request merged**
