### PR TITLE
[11.0][FIX] stock_picking_package_preparation_line: Do not delete lines when the picking is not removed

### PR DESCRIPTION
**Pull request by SimoRubi**
Forward port of https://github.com/OCA/stock-logistics-workflow/pull/472

### CODE REVIEW

**Comment by SimoRubi** [comment]
@eLBati @pedrobaeza forward porting the PR you approved a few days ago, could you please check?
Thanks!

**Review by pedrobaeza — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@SimoRubi Even if it is not documented like that in Odoo, the use of inverse attribute in standard fields allows not to override write() method. This allows readability.

**Comment by SimoRubi** [comment]
@rousseldenis do you mean that we might move everything that is in the `write` method in the `inverse` attribute of `picking_ids` field?
Thanks for the advice

**Comment by rousseldenis** [comment]
Not for this one, but yes it could be an alternative to override write() method which is not sometimes readable. If you read the code at https://github.com/odoo/odoo/blob/11.0/odoo/models.py#L3107, I think this is safe.

**Comment by SimoRubi** [comment]
ok I better get what you meant now, anyway I don't think using this _side effect_ of `inverse` field attribute could be said to be safe: it may change in future releases because the use you describe is not its real scope.
Anyway thanks for the insight in Odoo core code :)

**Pull request merged**
