### PR TITLE
Copier sync + switch to GH actions

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Comment by simahawk** [comment]
```
Run manifestoo -d . check-licenses
delivery_total_weight_from_packaging (LGPL-3) depends on product_total_weight_from_packaging (AGPL-3)
Error: Process completed with exit code 1.
```

**Comment by rousseldenis** [comment]
@simahawk Already done there : https://github.com/OCA/stock-logistics-workflow/pull/986

**Comment by simahawk** [comment]
@rousseldenis dammit, sorry I missed it :sweat: I'll open a PR to fix the license only then or I do everything here, as you prefer

**Comment by rousseldenis** [comment]
> @rousseldenis dammit, sorry I missed it sweat I'll open a PR to fix the license only then or I do everything here, as you prefer

If you are ok changing the license of delivery module to AGPL, I can do it now there.

**Comment by simahawk** [comment]
@rousseldenis feel free to pick the last 2 commits from here and close this.

**Comment by rousseldenis** [comment]
Switched to #986 

@simahawk I will merge it now

**Comment by simahawk** [comment]
arf, there are other modules w/ problems:

```
stock_partner_delivery_window (Beta) depends on partner_tz (Alpha)
stock_picking_group_by_partner_by_carrier (Beta) depends on delivery_procurement_group_carrier (Alpha)
```
we can upgrade the 2 Alpha to Beta

**Comment by rousseldenis** [comment]
> arf, there are other modules w/ problems:
> 
> ```
> stock_partner_delivery_window (Beta) depends on partner_tz (Alpha)
> stock_picking_group_by_partner_by_carrier (Beta) depends on delivery_procurement_group_carrier (Alpha)
> ```
> 
> we can upgrade the 2 Alpha to Beta

Yes, but there partner_tz is in different repo no ? I'd prefer switch to Alpha the problematic ones, merge, then, upgrade the other (not problematic in that way)

**Comment by simahawk** [comment]
partner_tz https://github.com/OCA/partner-contact/pull/1315

**Pull request closed without merging**
