### PR TITLE
port stock_picking_compute_delivery_date to v8

### PR DESCRIPTION
**Pull request by lepistone**
- [x] make tests pass
- [x] investigate tests passing only with admin
- [x] investigate multi-warehouse
- [x] document the changes in v8, bump version

### CODE REVIEW

**Comment by guewen** [comment]
:+1: 
Thanks

**Comment by guewen** [comment]
Error in travis:

```
2015-07-20 12:23:21,883 23920 DEBUG openerp_test openerp.tools.yaml_import: I create three incoming pickings for the same product. They could be generated by the Purchase Orders PO1, PO2, and PO3. We do not handle the orders here, except for the origin field.
2015-07-20 12:23:22,101 23920 DEBUG openerp_test openerp.tools.yaml_import: Creating !record {model: stock.move, id: move_in_1}:
with {'origin': 'PO1', 'name': 'line1 in', 'product_uom': 'product.product_uom_unit', 'product_qty': 10, 'picking_id': 'picking_in_1', 'product_id': 'product.product_product_48'}
2015-07-20 12:23:22,243 23920 ERROR openerp_test openerp.sql_db: bad query: INSERT INTO "stock_move" ("id", "origin", "product_uos_qty", "product_uom", "product_uom_qty", "procure_method", "product_qty", "product_uos", "location_id", "partner_id", "company_id", "priority", "state", "date_expected", "partially_available", "propagate", "date", "product_id", "name", "invoice_state", "location_dest_id", "group_id", "picking_id", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('stock_move_id_seq'), 'PO1', '1.000', 1, '1.000', 'make_to_stock', 10.0, NULL, NULL, NULL, 1, '1', 'draft', '2015-07-20 12:23:22', false, true, '2015-07-20 12:23:22', 54, 'line1 in', 'none', NULL, NULL, 50, 1, 1, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id
Traceback (most recent call last):
File "/home/travis/odoo-8.0/openerp/sql_db.py", line 234, in execute
res = self._obj.execute(query, params)
IntegrityError: null value in column "location_id" violates not-null constraint
```

**Comment by lepistone** [comment]
sorry @guewen, marked as WIP

**Comment by guewen** [comment]
Nice! thanks :+1:

**Comment by jgrandguillaume** [comment]
Hi,

Works like a charm, thanks !  :+1: 

Regards,

Joël

**Pull request merged**
