### PR TITLE
[15.0][MIG] stock_picking_mass_action: Migration to 15.0

### PR DESCRIPTION
**Pull request by theangryangel**
Largely standard migration.

I needed to make some small changes to accommodate `immediate_transfer_line_ids` and picking type `reservation_method`

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by CarlosRoca13** [comment]
Functional and code review :smile: :+1:

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
