### PR TITLE
[ADD] stock_traceability_internal: mandatory prodlot on internal moves

### LINKED ISSUE #5: Can't enforce internal traceability, even with product_serial
For the moment there seems to be no clear way of forcing users to enter lots/serial numbers on internal moves (see https://bugs.launchpad.net/openobject-addons/+bug/670451).
product_serial does create a field "track_internal" with a helptext that says it forces users to enter the serial number, but I found no code to support that.

### PR DESCRIPTION
**Pull request by clonedagain**
Fixes #5 by giving a basic implementation

### CODE REVIEW

**Comment by eLBati** [comment]
Thanks!
Some PEP8 remarks

```
./stock_traceability_internal/stock.py:33:20: E127 continuation line over-indented for visual indent
./stock_traceability_internal/stock.py:34:20: E127 continuation line over-indented for visual indent
./stock_traceability_internal/stock.py:35:20: E127 continuation line over-indented for visual indent
./stock_traceability_internal/stock.py:38:20: E127 continuation line over-indented for visual indent
```

Any chances to have tests? :smirk:

**Comment by pedrobaeza** [comment]
Code LGTM, but tests are very needed for this, because it changes a flow. 

Regards.

**Comment by clonedagain** [comment]
Thanks for your reviews.
Sorry I probably won't be able to update this until September (Numérigraphe is closing for August vacations).
PEP8: I hacked this in a bit a of a rush porting my v6 code. I'll that.
Tests: yes they would be required indeed. It would help me a lot if you'd be kind enough to propose a rough scenario I can implement.

**Comment by eLBati** [comment]
On 08/09/2014 01:11 AM, Lionel Sausin wrote:

> Thanks for your reviews.
> Sorry I probably won't be able to update this until September 
> (Numérigraphe is closing for August vacations).
> PEP8: I hacked this in a bit a of a rush porting my v6 code. I'll that.
> Tests: yes they would be required indeed. It would help me a lot if 
> you'd be kind enough to propose a rough scenario I can implement.

Something like
- Create product1 with 'Track Lots internally'
- Create an internal move for product1 without serial number -> the 
  system must block the user
- Create an internal move for product1 with serial number -> the 
  system must not block the user
- Create an inventory move for product1 without serial number -> the 
  system must not block the user
- Create an internal move for product1 without serial number and with 
  product_qty = 0 -> the system must not block the user
- Create product2 without 'Track Lots internally'
- Create an internal move for product2 without serial number -> the 
  system must not block the user

**Comment by lepistone** [comment]
The 7.0 branch is now green, please rebase on 7.0 so that we can see if this branch is green as well.

Thanks!

**Comment by clonedagain** [comment]
Rebased and fixed PEP8 - as it turns out my version of flake8 and autopep8 were obsolete so I didn't notice the problem at first.
I'll look into adding the test as soon as I can.

**Comment by clonedagain** [comment]
This needs more work, it seems to block manufacturing orders.
We'll need to add this scenario to the test too if we can.

**Comment by clonedagain** [comment]
We're moving to v8 where this modules won't be needed so I'm closing the PR, as we won't have an opportunity to make it right.

**Pull request closed without merging**
