### PR TITLE
[10.0][ADD]stock_picking_mass_return

### PR DESCRIPTION
**Pull request by MPoch-PlanetaTIC**
A wizard to select a supplier, a warehouse and a list of products with their quantities.
When clicking "Return Product" button a new stock picking out will be created to return the indicated products and quantites getting the stock from the last received purchases.

cc @PlanetaTIC

### CODE REVIEW

**Comment by rousseldenis** [comment]
@MPoch-PlanetaTIC Could you add tests ?

**Comment by rousseldenis** [comment]
@MPoch-PlanetaTIC What's the status of this ?

**Comment by MPoch-PlanetaTIC** [comment]
This module worked, but now we don't use it because we no longer use Odoo10.
And we haven't migrated it to new Odoo versions.

Feel free to do whatever you need to ;)

**Comment by rousseldenis** [comment]
Ok, so, closing as no interest from others

**Pull request closed without merging**
