### PR TITLE
[14.0][IMP] update copier template

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Comment by sergiocorato** [comment]
runboat check is failing (as in other 14.0 PRs) because it's not aware of rebels module, I think.
Is there a way to fix this problem?

**Comment by rousseldenis** [comment]
> runboat check is failing (as in other 14.0 PRs) because it's not aware of rebels module, I think. Is there a way to fix this problem?

@sergiocorato See my comment here : https://github.com/OCA/stock-logistics-workflow/pull/1271#issuecomment-1764742065

**Comment by rousseldenis** [comment]
@sergiocorato It seems pre-commit should be fixed

**Comment by sergiocorato** [comment]
> @sergiocorato It seems pre-commit should be fixed

Done, thanks!

**Comment by francesco-ooops** [comment]
@rousseldenis merge?

**Pull request merged**
