### PR TITLE
[15.0][MIG] stock_delivery_note: Migration to 15.0

### PR DESCRIPTION
**Pull request by janikvonrotz**
Standard migration from 14.0 to 15.0.

### CODE REVIEW

**Comment by janikvonrotz** [comment]
@pedrobaeza Can somebody check this PR or am I not following some guidelines here?

**Comment by pedrobaeza** [comment]
The pull request is only part of the contribution workflow. The reviews are also a voluntary effort by other contributors. You'll receive reviews if someone is interested in having the module in this version, or you can engage people reviewing other PRs and asking in exchange that they review yours.

/ocabot migration stock_delivery_note

**Comment by janikvonrotz** [comment]
@pedrobaeza Thank you for your feedback.

> you can engage people reviewing other PRs and asking in exchange that they review yours.

Good point here. I will try to engage more.

**Review by rousseldenis — APPROVED** [review]

**Comment by janikvonrotz** [comment]
@rousseldenis Thank you very much.

**Review by Shide — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@rousseldenis What is the status of this one?

**Comment by rousseldenis** [comment]
@janikvonrotz Could you rebase without merging as this should be avoided :

image

**Comment by janikvonrotz** [comment]
Ooops.

**Comment by janikvonrotz** [comment]
Superseeded by #1270

**Pull request closed without merging**
