### PR TITLE
[17.0] [MIG] sale_order_global_stock_route: Migration to 17.0

### PR DESCRIPTION
**Pull request by DrHohol**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@DrHohol Thanks for this. Could you follow this https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch ?

**Comment by DrHohol** [comment]
> @DrHohol Thanks for this. Could you follow this https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch ?

Hi @rousseldenis. Changed the commit according to your message

**Comment by rousseldenis** [comment]
> > @DrHohol Thanks for this. Could you follow this https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch ?
> 
> Hi @rousseldenis. Changed the commit according to your message

Nope. You should respect the commit history

**Pull request closed without merging**
