### PR TITLE
[16.0][MIG] stock_picking_mass_action: Migration to 16.0

### PR DESCRIPTION
**Pull request by pausanchezqubiq**

### CODE REVIEW

**Comment by JSebastian7913** [comment]
Functional validation done.

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by dsolanki-initos — CHANGES_REQUESTED** [review]
During module functional testing found that Odoo standard already provides the functionality of `Check Availability` in list view of the Stock picking, thus there is no need for server action of `Check Availability` feature in this module.

**Comment by rousseldenis** [comment]
@pausanchezqubiq Do you mind if we switch to #1405 ?

**Pull request closed without merging**
