### PR TITLE
8.0 fix stock default ownership multi company

### PR DESCRIPTION
**Pull request by lmignon**
@lepistone Your advice would be welcome. This one is crucial in a multi company env.

### CODE REVIEW

**Comment by phschmidt** [comment]
:+1: Functional tests showed that the issue is completely corrected.

**Comment by lepistone** [comment]
:+1: thanks!

**Comment by pedrobaeza** [comment]
Why is Travis red?

**Comment by lmignon** [comment]
@pedrobaeza The error is in `stock_split_picking`. I haven't investigated to see if this error is related to this PR ... I'll at first rebase the branch...

**Comment by lmignon** [comment]
@pedrobaeza rebase done.  The failing tests should be fixed thanks to the merge of https://github.com/OCA/stock-logistics-workflow/pull/205

**Comment by lmignon** [comment]
@pedrobaeza Travis is  green.

**Comment by pedrobaeza** [comment]
Thanks, I'm waiting the runbot result because it says it needs `base_multi_image` (nothing to do with your PR, but I want to let a clear runbot also).

**Comment by lmignon** [comment]
@pedrobaeza As you said nothing related to this PR and frustrating to have a PR blocked for something outside of this PR.

**Comment by pedrobaeza** [comment]
It's not blocked. It's only staled for 10 minutes more. Please wait.

**Comment by pedrobaeza** [comment]
OK, I have added the dependency, so I can merge and the new 8.0 runbot instance will be green.

Merging...

**Comment by lmignon** [comment]
@pedrobaeza Thank you.

**Pull request merged**
