### PR TITLE
[15.0][FIX] stock_picking_invoice_link: Users without stock group can not view pickings. So hide button picking in invoice view

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT44565

ping @chienandalu @CarlosRoca13

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Just that the commit message would be *users **without** stock group...* wouldn't it?

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Done!! @chienandalu jajaja

**Comment by pedrobaeza** [comment]
@sergio-teruel can you please cherry-pick this to v16?

**Pull request merged**
