### PR TITLE
[MIG] stock_quant_package_dimension: Migration to 16.0

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

- [ ] https://github.com/OCA/stock-logistics-workflow/pull/1103
- [ ] https://github.com/OCA/product-attribute/pull/1161

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
LGTM (Code review)

**Comment by lmignon** [comment]
@rousseldenis A rebase would make CI :green_circle:

**Review by sebalix — APPROVED** [review]

**Pull request merged**
