### PR TITLE
[16.0][MIG] stock_picking_mass_action: Migration to version 16.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v16.
- Remove functionality Check availabilty as it is added on tree view as an standard functionality on version 16.
- Supersedes https://github.com/OCA/stock-logistics-workflow/pull/1308 due to inactivity

TT44366

@Tecnativa

@pedrobaeza @carlosdauden

### CODE REVIEW

**Comment by rousseldenis** [comment]
@carolinafernandez-tecnativa Thanks for this. Usually, when a PR exists, it is fair to start from there (and crediting contributor).

**Comment by carolinafernandez-tecnativa** [comment]
> @carolinafernandez-tecnativa Thanks for this. Usually, when a PR exists, it is fair to start from there (and crediting contributor).

Thanks! I just added the contributor as in other PR

**Comment by pedrobaeza** [comment]
@rousseldenis was talking about cherry-picking their commit, not to add it as contributor in the README (which can also be done, of course).

**Comment by pedrobaeza** [comment]
I still see your changes as predominant. You should:

- Remove your commit (you can save the contents).
- Cherry-pick the other commit.
- Add your changes and commit.

**Comment by carolinafernandez-tecnativa** [comment]
> I still see your changes as predominant. You should:
> 
> * Remove your commit (you can save the contents).
> * Cherry-pick the other commit.
> * Add your changes and commit.

Could you please check it now? Thanks :)

**Review by pedrobaeza — APPROVED** [review]

**Comment by FranciscoFactorLibre** [comment]
I have carried out a functional review, and it seems correct.

Can you check from your side @carlosdauden ?

Thanks

**Comment by legalsylvain** [comment]
@FranciscoFactorLibre, could you approve via github, to make the PR approved ?

**Review by FranciscoFactorLibre — APPROVED** [review]
I have carried out a functional review, and it seems correct.

Thanks

**Pull request merged**
