### PR TITLE
9.0 stock picking invoice link

### PR DESCRIPTION
**Pull request by hendrixcosta**

### CODE REVIEW

**Comment by hendrixcosta** [comment]
#246

**Comment by mileo** [comment]
Replace #246 :+1:

**Review by eLBati — APPROVED** [review]
Thanks

**Review by pedrobaeza — APPROVED** [review]

**Comment by jbaudoux** [comment]
The port of this module doesn't allow anymore to find out the related moved that are invoiced. If you have 2 deliveries, it seems by reading the code, that the 2 invoices will point to the 2 deliveries and not the related one.
I'll make a PR that fix this.

**Pull request merged**
