### PR TITLE
[9.0][REF]stock_pack_operation_auto_fill: move auto fill button to header

### PR DESCRIPTION
**Pull request by zakiuu**
Move the auto fill button from the operation tab to the picking form header

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
:+1: 
Do you plan a forward port to 10?

**Comment by zakiuu** [comment]
@rousseldenis Thanks for the review, and for your question, yeah maybe in the next OCA code sprint

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by lmignon — APPROVED** [review]
Tested on runbot

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by zakiuu** [comment]
@pedrobaeza This one is ready to be merged

**Review by benwillig — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please remember other times to change module version number

**Pull request merged**
