### PR TITLE
[9.0][IMP] stock_deposit: Allow select quantities to regularize in each selected quant

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa
WIP: todo: more tests

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please fix Travis and add some tests.

**Comment by MiquelRForgeFlow** [comment]
@sergio-teruel please, rebase the PR :wink:

**Comment by sergio-teruel** [comment]
@mreficent rebase done

**Comment by pedrobaeza** [comment]
Travis is still failing.

**Comment by sergio-teruel** [comment]
Yes, due to srock_account_deposit... 
Can i do change tow modules with the same PR?

**Comment by pedrobaeza** [comment]
Well, put it in another commit and it will be fine.

**Comment by sergio-teruel** [comment]
@pedrobaeza changes done

**Review by pedrobaeza — APPROVED** [review]
@chienandalu please review

**Review by chienandalu — APPROVED** [review]
Tested on runbot. Maybe it's worth mentioning the new feature in the README, isn't it?

**Comment by pedrobaeza** [comment]
Please adapt README before merging.

**Comment by sergio-teruel** [comment]
@chienandalu @pedrobaeza Changes on readme done

**Comment by pedrobaeza** [comment]
Please squash both commits and change module version number before merging.

**Comment by sergio-teruel** [comment]
@pedrobaeza Changes done

**Pull request merged**
