### PR TITLE
[9.0][FIX] stock_account_deposit: Fix invalidate option "only regularize" is this module is installed

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by yvaucher** [comment]
Please fix the test error:

```
2017-06-20 11:37:41,015 5753 ERROR openerp_test openerp.addons.stock_account_deposit.tests.test_stock_account_deposit: ` ValidationError: (u"You cannot validate this stock operation because the stock level of the product 'Product - Deposit - Test' would become negative on the stock location 'Physical Locations/WH-TEST/Stock' and negative stock is not allowed for this product.", None)
```

To do so you need to add the following in .travis.yml

```
- TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE=stock_no_negative
- TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE=stock_no_negative
- TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE=stock_no_negative
- TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE=stock_no_negative
```

Or ensure that your test comply with the stock_no_negative module constraint if you can.

**Comment by pedrobaeza** [comment]
I think it's better to disable stock_no_negative warning on test mode if not testing the module itself, similar as it's done in https://github.com/OCA/bank-payment/blob/8.0/account_payment_transfer_reconcile_batch/models/payment_order.py#L28

**Comment by MiquelRForgeFlow** [comment]
@sergio-teruel  please, rebase the PR 😉

**Comment by sergio-teruel** [comment]
@mreficent rebase done..

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
