### PR TITLE
[12.0][MIG] stock_picking_purchase_propagate

### PR DESCRIPTION
**Pull request by kittiu**
Dependencies
- [x] purchase_line_procurement_group https://github.com/OCA/purchase-workflow/pull/672

### CODE REVIEW

**Comment by kittiu** [comment]
Done migrated.

**Review by HaraldPanten — APPROVED** [review]
Functional review. Seems OK for me 👍

**Comment by kos94ok-3D** [comment]
Hi, @kittiu 
Can you restore history commits?

**Comment by kittiu** [comment]
@kos94ok-3D @HaraldPanten
Done restore history. I will close this PR and move to https://github.com/OCA/stock-logistics-workflow/pull/591
Please approve again, thank you.

**Pull request closed without merging**
