### PR TITLE
[16.0][MIG] stock_picking_back2draft

### PR DESCRIPTION
**Pull request by otmanelagy**

### CODE REVIEW

**Comment by otmanelagy** [comment]
please Review

**Comment by otmanelagy** [comment]
cc @rousseldenis @jbaudoux

**Review by rousseldenis — APPROVED** [review]
LGTM.

@otmanelagy For the next migration PR, put the version change in the migration commit, not in pre-commit one.

**Comment by otmanelagy** [comment]
@rousseldenis well noted , thanks!

**Comment by otmanelagy** [comment]
@rousseldenis @sebalix  , its need to be merged?

**Review by sebalix — APPROVED** [review]

**Pull request merged**
