### PR TITLE
[10.0][FIX]stock_cancel

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Not admin users cannot reopen pickings

### CODE REVIEW

**Review by rousseldenis — CHANGES_REQUESTED** [review]
LGTM. Could you update module version?

**Comment by rousseldenis** [comment]
@aheficent Apart of this, during 10.0 migration, you changed licensing headers to LGPL. This led to inconsistency with manifest key (AGPL).

https://github.com/OCA/stock-logistics-workflow/pull/418

Could you clarify and update that too ?

**Comment by AaronHForgeFlow** [comment]
@rousseldenis probably was copy/paste issue. I will fix that.

**Comment by rousseldenis** [comment]
@aheficent

**Review by rousseldenis — APPROVED** [review]

**Comment by rousseldenis** [comment]
We can merge this

**Pull request closed without merging**
