### PR TITLE
Correctly group move IDs depending on product and location

### PR DESCRIPTION
**Pull request by mdietrichc2c**
8.0 version of PR https://github.com/OCA/stock-logistics-workflow/pull/207

### CODE REVIEW

**Comment by jcoux** [comment]
:+1:

**Comment by lepistone** [comment]
:+1: thanks!

**Comment by cyrilgdn** [comment]
After some tests, checking availability doesn't seems to work in V8, the action_assign_moves call _product_reserve on stock.location but this method does not exists anymore!

I will create a new PR to revert the PR #123 (migration of the dispatch optimisation from V7 to V8) but i think this one should be cancel.

**Comment by gurneyalex** [comment]
revert PR is #210

**Pull request closed without merging**
