### PR TITLE
[14.0][MIG] procurement_auto_create_group_carrier

### PR DESCRIPTION
**Pull request by hailangvn**
Depends on:
* `procurement_auto_create_group`: https://github.com/OCA/stock-logistics-warehouse/pull/1271

### CODE REVIEW

**Review by simahawk — COMMENTED** [review]
LG

**Comment by sebalix** [comment]
@hailangvn https://github.com/OCA/stock-logistics-warehouse/pull/1271 has been merged, you can update your PR

**Comment by hailangvn** [comment]
Thanks @sebalix, the PR has been updated.

**Review by rousseldenis — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
