### PR TITLE
WIP: [ADD] partner_credit_limit

### PR DESCRIPTION
**Pull request by max3903**
https://github.com/OCA/l10n-usa/issues/5

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, @max3903, we have already a set of modules for this task in 9.0. The main one is already merged in https://github.com/OCA/partner-contact/tree/9.0/partner_financial_risk, and a migration to 10.0 is in course here: https://github.com/OCA/partner-contact/pull/360. For something similar to this, you have https://github.com/OCA/partner-contact/pull/300, and another one at sales level with https://github.com/OCA/partner-contact/pull/295

**Comment by max3903** [comment]
@pedrobaeza Thanks. I will check.

**Comment by rousseldenis** [comment]
@max3903 WIP ?

**Comment by max3903** [comment]
@rousseldenis aha :) Not much progress unfortunately...

**Comment by rousseldenis** [comment]
@max3903 Ok. I didn't catch @pedrobaeza comments

**Comment by pedrobaeza** [comment]
@rousseldenis they are now hosted for v11 in https://github.com/OCA/credit-control/

**Pull request closed without merging**
