### PR TITLE
[FIX] stock_picking_start: fix user_id vals in _prepare_start_values

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sbejaoui Could you rebase ?

**Review by rousseldenis — APPROVED** [review]

**Comment by sbejaoui** [comment]
> @sbejaoui Could you rebase ?

done

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
@rousseldenis Can you merge this one PLZ?

**Pull request merged**
