### PR TITLE
[16.0][MIG] product_expiry_simple

### PR DESCRIPTION
**Pull request by alexis-via**
I migrated the module in october 2022, but it seems that I forgot to make the PR... sorry about that.

### CODE REVIEW

**Comment by rafaelbn** [comment]
@alexis-via please, could you rebase? and check if all is green? 🍏 Thank you!

**Comment by alexis-via** [comment]
@rafaelbn done

**Review by mourad-ehm — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]

**Comment by hparfr** [comment]
>odoo.exceptions.UserError: Modules "Product Expiry Simple" and "Products Expiration Date" are incompatible.

**Comment by alexis-via** [comment]
@hparfr yes, it's intended !

**Comment by alexis-via** [comment]
@bosd here is an example for you when you have a module that is incompatible with another module of the same repo and you need to have the tests green.

**Comment by rousseldenis** [comment]
@sbidoul Do we have a solution for incompatible modules? I remember that if we want to keep runboat running, this kind of module should have its specific repository.

**Comment by alexis-via** [comment]
I am the declared maintainer of product_expiry_simple, cf https://github.com/OCA/stock-logistics-workflow/blob/14.0/product_expiry_simple/__manifest__.py
Where is this stupid bot reading the information about the declared maintainer ??

**Comment by sbidoul** [comment]
> Do we have a solution for incompatible modules? I remember that if we want to keep runboat running, this kind of module should have its specific repository.

@rousseldenis you may remember this: https://github.com/sbidoul/runboat/pull/95

**Comment by rousseldenis** [comment]
@alexis-via Could you rebase to move forward on this as runboat has now two databases (one with all modules, one just with 'base') ?

**Comment by alexis-via** [comment]
rebased

**Comment by rousseldenis** [comment]
@alexis-via Could you rebase again ?

**Comment by alexis-via** [comment]
rebase done

**Comment by rousseldenis** [comment]
@alexis-via Could you just let me know what was blocking in tests to have this seggregated in separate test flow (as I see you use the 'use_expiry_date`for constraint checks, so it shouldn't block other tests?

**Comment by alexis-via** [comment]
@rousseldenis either you install product_expiry OR product_expiry_simple, but not both ! In the manifest of product_expiry_simple, I added 
```
"excludes": ["product_expiry"]
```

**Pull request merged**
