### PR TITLE
[FIX] stock_batch_picking: use of OrderedDict to get sorted operations

### PR DESCRIPTION
**Pull request by sebalix**
on the report (as dictionaries are not sorted on Python 2).

Related to https://github.com/OCA/stock-logistics-workflow/pull/574/files

### CODE REVIEW

**Comment by sebalix** [comment]
ping @i-vyshnevska @andreampiovesana @rousseldenis

**Review by i-vyshnevska — APPROVED** [review]

**Comment by rousseldenis** [comment]
@sebalix Could you highlight this change with a test ?

**Comment by sebalix** [comment]
@rousseldenis test added

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
