### PR TITLE
[17.0][MIG] stock_picking_return_lot: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 162161
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/stock-logistics-workflow/issues/1421

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat and working as expected

**Review by rousseldenis — APPROVED** [review]
LGTM. Thanks !

**Comment by peluko00** [comment]
Seems it's ready to merge @rousseldenis, i need this module for migrate rma_lot to v17

**Review by hparfr — COMMENTED** [review]
/ocabot merge nobump

**Pull request merged**
