### PR TITLE
[14.0][FIX] stock_putaway_by_route is not an application

### PR DESCRIPTION
**Pull request by andreampiovesana**
fix manifest because is not an application

### CODE REVIEW

**Comment by legalsylvain** [comment]
I'm curious to know why it is a problem.

**Comment by andreampiovesana** [comment]
it is a small fix, the reason is evident.

**Comment by legalsylvain** [comment]
>  the reason is evident.

thank you for this very complete answer. ;-)

**Comment by rousseldenis** [comment]
> > the reason is evident.
> 
> thank you for this very complete answer. ;-)

Arf. I think that the answer is the module is an 'accessory' module for a bigger application (e.g.: stock).

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
