### PR TITLE
[ADD] - Added new module stock_analytic

### PR DESCRIPTION
**Pull request by fv-clearcorp**
This module allows the user to generate analytic information from stock
moves.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this go to OCA/account-analytic?

**Comment by andhit-r** [comment]
@fv-clearcorp @pedrobaeza  can I offer You help to move this module into OCA/account-analytic? I will preserve commit history

**Comment by pedrobaeza** [comment]
Yes, please!

**Comment by andhit-r** [comment]
@pedrobaeza I have moved this module on https://github.com/OCA/account-analytic/pull/52. I use https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA technique to preserve commit history.

**Comment by pedrobaeza** [comment]
We can close this then.

**Pull request closed without merging**
