### PR TITLE
[14.0][MIG] stock_account_product_run_fifo_hook: migration from 13.0 to 14.0

### PR DESCRIPTION
**Pull request by AlvaroTForgeFlow**
@ForgeFlow

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@AlvaroTForgeFlow Could you adjust the title of the PR and have 2 migration commits (one for pre-commit and so on, and the other for actual migration) (see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)?

Thanks!

**Comment by AlvaroTForgeFlow** [comment]
> @AlvaroTForgeFlow Could you adjust the title of the PR and have 2 migration commits (one for pre-commit and so on, and the other for actual migration) (see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0)?
> 
> Thanks!

Done.

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
@LoisRForgeFlow can you close this one? It is superseded here: https://github.com/OCA/stock-logistics-workflow/pull/1004 and in that PR it was better tested.

**Comment by dreispt** [comment]
Superseded

**Pull request closed without merging**
